INTERFACE

SUBROUTINE TURB(CST,CSTURB,TURBN,NEBN,D,TLES,            &
& KRR,KRRL,KRRI,HLBCX,HLBCY,KGRADIENTSLEO,              &
& KGRADIENTSGOG,KHALO,                                  &
& KSPLIT, OCLOUDMODIFLM, KSV,KSV_LGBEG,KSV_LGEND,       &
& KSV_LIMA_NR, KSV_LIMA_NS, KSV_LIMA_NG, KSV_LIMA_NH,   &
& O2D,ONOMIXLG,OFLAT,OCOUPLES,OBLOWSNOW,OIBM,OFLYER,    &
& OCOMPUTE_SRC, PRSNOW,                                 &
& OOCEAN,ODEEPOC,ODIAG_IN_RUN,                          &
& HTURBLEN_CL,HCLOUD,HELEC,                             &
& PTSTEP,TPFILE,                                        &
& PDXX,PDYY,PDZZ,PDZX,PDZY,PZZ,                         &
& PDIRCOSXW,PDIRCOSYW,PDIRCOSZW,PCOSSLOPE,PSINSLOPE,    &
& PRHODJ,PTHVREF,PHGRADLEO,PHGRADGOG,PZS,               &
& PSFTH,PSFRV,PSFSV,PSFU,PSFV,                          &
& PPABST,PUT,PVT,PWT,PTKET,PSVT,PSRCT,                  &
& PLENGTHM,PLENGTHH,MFMOIST,                            &
& PBL_DEPTH,PSBL_DEPTH,                                 &
& PCEI,PCEI_MIN,PCEI_MAX,PCOEF_AMPL_SAT,                &
& PTHLT,PRT,                                            &
& PRUS,PRVS,PRWS,PRTHLS,PRRS,PRSVS,PRTKES,              &
& PSIGS,                                                &
& PFLXZTHVMF, PFLXZUMF, PFLXZVMF,                       &
& PWTH,PWRC,PWSV,PDP,PTP,PTDIFF,PTDISS,      &
& KBUDGETS,                                   &
& PEDR,PLEM,PRTKEMS,PDPMF,PTPMF,                        &
& PDRUS_TURB,PDRVS_TURB,                                &
& PDRTHLS_TURB,PDRRTS_TURB,PDRSVS_TURB,PTR,PDISS,       &
& PIBM_LS, PIBM_XMUT,                                   &
& PCURRENT_TKE_DISS, PSSTFL, PSSTFL_C, PSSRFL_C,        &
& PSSUFL_C, PSSVFL_C,PSSUFL,PSSVFL                      )
USE MODD_CST,        ONLY: CST_T
USE MODD_CTURB,      ONLY: CSTURB_T
USE MODD_DIMPHYEX,   ONLY: DIMPHYEX_T
USE MODD_IO,         ONLY: TFILEDATA
USE MODD_LES,        ONLY: TLES_T
USE MODD_TURB_N,     ONLY: TURB_T
USE MODD_NEB_N,      ONLY: NEB_T
USE MODI_LES_MEAN_SUBGRID_PHY
IMPLICIT NONE
TYPE(DIMPHYEX_T),       INTENT(IN)   :: D
TYPE(CST_T),            INTENT(IN)   :: CST
TYPE(CSTURB_T),         INTENT(IN)   :: CSTURB
TYPE(TURB_T),           INTENT(IN)   :: TURBN
TYPE(NEB_T),            INTENT(IN)   :: NEBN
TYPE(TLES_T),           INTENT(INOUT)   :: TLES
INTEGER,                INTENT(IN)   :: KGRADIENTSLEO
INTEGER,                INTENT(IN)   :: KGRADIENTSGOG
INTEGER,                INTENT(IN)   :: KRR
INTEGER,                INTENT(IN)   :: KRRL
INTEGER,                INTENT(IN)   :: KRRI
INTEGER,                INTENT(IN)   :: KSV, KSV_LGBEG, KSV_LGEND
INTEGER,                INTENT(IN)   :: KSV_LIMA_NR,KSV_LIMA_NS,KSV_LIMA_NG,KSV_LIMA_NH
CHARACTER(LEN=4),DIMENSION(2),INTENT(IN):: HLBCX, HLBCY
INTEGER,                INTENT(IN)   :: KSPLIT
LOGICAL,                INTENT(IN)   :: OCLOUDMODIFLM
INTEGER,                INTENT(IN)   ::  KHALO
LOGICAL,                INTENT(IN)   ::  OCOMPUTE_SRC
LOGICAL,                INTENT(IN)   ::  OOCEAN
LOGICAL,                INTENT(IN)   ::  ODEEPOC
LOGICAL,                INTENT(IN)   ::  OFLYER
LOGICAL,                INTENT(IN)   ::  OFLAT
LOGICAL,                INTENT(IN)   ::  OCOUPLES
LOGICAL,                INTENT(IN)   ::  OBLOWSNOW
LOGICAL,                INTENT(IN)   ::  ODIAG_IN_RUN
LOGICAL,                INTENT(IN)   ::  OIBM
CHARACTER(LEN=4),       INTENT(IN)   ::  HTURBLEN_CL
CHARACTER (LEN=4),      INTENT(IN)   ::  HCLOUD
CHARACTER (LEN=4),      INTENT(IN)   ::  HELEC
REAL,                   INTENT(IN)   ::  PRSNOW
REAL,                   INTENT(IN)   ::  PTSTEP
TYPE(TFILEDATA),        INTENT(INOUT)   ::  TPFILE
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN)   :: PDXX,PDYY,PDZZ,PDZX,PDZY
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN)   :: PZZ
REAL, DIMENSION(D%NIJT),   INTENT(IN)      ::  PDIRCOSXW, PDIRCOSYW, PDIRCOSZW
REAL, DIMENSION(D%NIJT),   INTENT(IN)   ::  PCOSSLOPE
REAL, DIMENSION(D%NIJT),   INTENT(IN)   ::  PSINSLOPE
REAL, DIMENSION(D%NIJT),   INTENT(IN)   ::  PZS
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN)      ::  PRHODJ
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN)      ::  MFMOIST
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN)      ::  PTHVREF
REAL, DIMENSION(D%NIJT,D%NKT,KGRADIENTSLEO),   INTENT(IN) ::  PHGRADLEO
REAL, DIMENSION(D%NIJT,D%NKT,KGRADIENTSGOG),   INTENT(IN) ::  PHGRADGOG
REAL, DIMENSION(D%NIJT),   INTENT(IN)      ::  PSFTH,PSFRV,   &
PSFU,PSFV
REAL, DIMENSION(D%NIJT,KSV), INTENT(IN)      ::  PSFSV
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN) ::  PPABST
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN) ::  PUT,PVT,PWT
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN) ::  PTKET
REAL, DIMENSION(D%NIJT,D%NKT,KSV), INTENT(IN) ::  PSVT
REAL, DIMENSION(MERGE(D%NIJT,0,OCOMPUTE_SRC),&
MERGE(D%NKT,0,OCOMPUTE_SRC)),   INTENT(IN) ::  PSRCT
REAL, DIMENSION(D%NIJT),INTENT(INOUT) :: PBL_DEPTH
REAL, DIMENSION(D%NIJT),INTENT(INOUT) :: PSBL_DEPTH
REAL, DIMENSION(MERGE(D%NIJT,0,OCLOUDMODIFLM),&
MERGE(D%NKT,0,OCLOUDMODIFLM)),INTENT(IN)      ::  PCEI
REAL, INTENT(IN)      ::  PCEI_MIN
REAL, INTENT(IN)      ::  PCEI_MAX
REAL, INTENT(IN)      ::  PCOEF_AMPL_SAT
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(INOUT) ::  PTHLT
REAL, DIMENSION(D%NIJT,D%NKT,KRR), INTENT(INOUT) ::  PRT
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(INOUT) ::  PRUS,PRVS,PRWS,PRTHLS,PRTKES
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN),OPTIONAL    ::  PRTKEMS
REAL, DIMENSION(D%NIJT,D%NKT,KRR), INTENT(INOUT) ::  PRRS
REAL, DIMENSION(D%NIJT,D%NKT,KSV), INTENT(INOUT) ::  PRSVS
REAL, DIMENSION(MERGE(D%NIJT,0,OCOMPUTE_SRC),&
MERGE(D%NKT,0,OCOMPUTE_SRC)), INTENT(OUT)     ::  PSIGS
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT),OPTIONAL     ::  PDRUS_TURB
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT),OPTIONAL     ::  PDRVS_TURB
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT),OPTIONAL     ::  PDRTHLS_TURB
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT),OPTIONAL     ::  PDRRTS_TURB
REAL, DIMENSION(D%NIJT,D%NKT,KSV), INTENT(OUT),OPTIONAL ::  PDRSVS_TURB
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN)      ::  PFLXZTHVMF
REAL, DIMENSION(MERGE(D%NIJT,0,OFLYER),MERGE(D%NKT,0,OFLYER)), INTENT(OUT)  :: PWTH
REAL, DIMENSION(MERGE(D%NIJT,0,OFLYER),MERGE(D%NKT,0,OFLYER)), INTENT(OUT)  :: PWRC
REAL, DIMENSION(MERGE(D%NIJT,0,OFLYER),MERGE(D%NKT,0,OFLYER),MERGE(KSV,0,OFLYER)),INTENT(OUT) :: PWSV
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN)   :: PFLXZUMF
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN)   :: PFLXZVMF
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT)  :: PTP
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT),OPTIONAL  :: PTPMF
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT)  :: PDP
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT),OPTIONAL  :: PDPMF
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT)  :: PTDIFF
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT)  :: PTDISS
INTEGER, INTENT(IN) :: KBUDGETS
LOGICAL, INTENT(IN) :: ONOMIXLG
LOGICAL, INTENT(IN) :: O2D
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN)    :: PLENGTHM, PLENGTHH
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT), OPTIONAL  :: PEDR
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT), OPTIONAL  :: PLEM
REAL, DIMENSION(D%NIJT,D%NKT),  INTENT(OUT), OPTIONAL  ::  PTR
REAL, DIMENSION(D%NIJT,D%NKT),  INTENT(OUT), OPTIONAL  ::  PDISS
REAL, DIMENSION(MERGE(D%NIJT,0,ODIAG_IN_RUN),MERGE(D%NKT,0,ODIAG_IN_RUN)), INTENT(INOUT), OPTIONAL  ::  PCURRENT_TKE_DISS
REAL, DIMENSION(MERGE(D%NIJT,0,OCOUPLES)), INTENT(IN),OPTIONAL   ::  PSSTFL
REAL, DIMENSION(MERGE(D%NIJT,0,OCOUPLES)), INTENT(IN),OPTIONAL   ::  PSSTFL_C
REAL, DIMENSION(MERGE(D%NIJT,0,OCOUPLES)), INTENT(IN),OPTIONAL   ::  PSSRFL_C
REAL, DIMENSION(MERGE(D%NIJT,0,OCOUPLES)), INTENT(IN),OPTIONAL   ::  PSSUFL_C
REAL, DIMENSION(MERGE(D%NIJT,0,OCOUPLES)), INTENT(IN),OPTIONAL   ::  PSSVFL_C
REAL, DIMENSION(MERGE(D%NIJT,0,OCOUPLES)), INTENT(IN),OPTIONAL   ::  PSSUFL
REAL, DIMENSION(MERGE(D%NIJT,0,OCOUPLES)), INTENT(IN),OPTIONAL   ::  PSSVFL
REAL, DIMENSION(MERGE(D%NIJT,0,OIBM),MERGE(D%NKT,0,OIBM)), INTENT(OUT), OPTIONAL :: PIBM_XMUT
REAL, DIMENSION(MERGE(D%NIJT,0,OIBM),MERGE(D%NKT,0,OIBM)), INTENT(IN), OPTIONAL  :: PIBM_LS
END SUBROUTINE TURB







END INTERFACE
