MODULE UTIL_DIMPHYEX_T_MOD

USE MODD_DIMPHYEX, ONLY : DIMPHYEX_T

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_DIMPHYEX_T
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_DIMPHYEX_T
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_DIMPHYEX_T
END INTERFACE




INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_DIMPHYEX_T
END INTERFACE


CONTAINS

SUBROUTINE ACDC_SAVE_DIMPHYEX_T (SELF, KLUN)

IMPLICIT NONE
TYPE (DIMPHYEX_T), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%NIT
WRITE (KLUN) SELF%NIB
WRITE (KLUN) SELF%NIE
WRITE (KLUN) SELF%NJT
WRITE (KLUN) SELF%NJB
WRITE (KLUN) SELF%NJE
WRITE (KLUN) SELF%NKL
WRITE (KLUN) SELF%NKT
WRITE (KLUN) SELF%NKLES
WRITE (KLUN) SELF%NKA
WRITE (KLUN) SELF%NKU
WRITE (KLUN) SELF%NKB
WRITE (KLUN) SELF%NKE
WRITE (KLUN) SELF%NKTB
WRITE (KLUN) SELF%NKTE
WRITE (KLUN) SELF%NIBC
WRITE (KLUN) SELF%NJBC
WRITE (KLUN) SELF%NIEC
WRITE (KLUN) SELF%NJEC
WRITE (KLUN) SELF%NIJT
WRITE (KLUN) SELF%NIJB
WRITE (KLUN) SELF%NIJE
WRITE (KLUN) SELF%NLESMASK
WRITE (KLUN) SELF%NLES_TIMES
END SUBROUTINE

SUBROUTINE ACDC_LOAD_DIMPHYEX_T (SELF, KLUN)

IMPLICIT NONE
TYPE (DIMPHYEX_T), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%NIT
READ (KLUN) SELF%NIB
READ (KLUN) SELF%NIE
READ (KLUN) SELF%NJT
READ (KLUN) SELF%NJB
READ (KLUN) SELF%NJE
READ (KLUN) SELF%NKL
READ (KLUN) SELF%NKT
READ (KLUN) SELF%NKLES
READ (KLUN) SELF%NKA
READ (KLUN) SELF%NKU
READ (KLUN) SELF%NKB
READ (KLUN) SELF%NKE
READ (KLUN) SELF%NKTB
READ (KLUN) SELF%NKTE
READ (KLUN) SELF%NIBC
READ (KLUN) SELF%NJBC
READ (KLUN) SELF%NIEC
READ (KLUN) SELF%NJEC
READ (KLUN) SELF%NIJT
READ (KLUN) SELF%NIJB
READ (KLUN) SELF%NIJE
READ (KLUN) SELF%NLESMASK
READ (KLUN) SELF%NLES_TIMES
END SUBROUTINE

SUBROUTINE ACDC_COPY_DIMPHYEX_T (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (DIMPHYEX_T), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE







SUBROUTINE ACDC_WIPE_DIMPHYEX_T (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (DIMPHYEX_T), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
