MODULE UTIL_TFILEDATA_MOD

USE MODD_IO, ONLY : TFILEDATA

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_TFILEDATA
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_TFILEDATA
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_TFILEDATA
END INTERFACE




INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_TFILEDATA
END INTERFACE


CONTAINS

SUBROUTINE ACDC_SAVE_TFILEDATA (SELF, KLUN)

IMPLICIT NONE
TYPE (TFILEDATA), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%LOPENED
WRITE (KLUN) SELF%NLU
END SUBROUTINE

SUBROUTINE ACDC_LOAD_TFILEDATA (SELF, KLUN)

IMPLICIT NONE
TYPE (TFILEDATA), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%LOPENED
READ (KLUN) SELF%NLU
END SUBROUTINE

SUBROUTINE ACDC_COPY_TFILEDATA (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TFILEDATA), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE







SUBROUTINE ACDC_WIPE_TFILEDATA (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TFILEDATA), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
