MODULE MODE_MODULE2

IMPLICIT NONE

CONTAINS

SUBROUTINE MODULE2_SUB1(A)

USE YOMHOOK,    ONLY: LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE

REAL, INTENT(INOUT) :: A

IF (LHOOK) CALL DR_HOOK('MODULE2_SUB1',0,ZHOOK_HANDLE)

IF (LHOOK) CALL DR_HOOK('MODULE2_SUB1',1,ZHOOK_HANDLE)

END SUBROUTINE MODULE2_SUB1

!=====================

SUBROUTINE MODULE2_SUB2(A)

USE YOMHOOK,    ONLY: LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE

REAL, INTENT(INOUT) :: A

IF (LHOOK) CALL DR_HOOK('MODULE2_SUB1',0,ZHOOK_HANDLE)

IF (LHOOK) CALL DR_HOOK('MODULE2_SUB1',1,ZHOOK_HANDLE)

END SUBROUTINE MODULE2_SUB2

!=====================

SUBROUTINE MODULE2_SUB3(A)

USE YOMHOOK,    ONLY: LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE

REAL, INTENT(INOUT) :: A

IF (LHOOK) CALL DR_HOOK('MODULE2_SUB1',0,ZHOOK_HANDLE)

IF (LHOOK) CALL DR_HOOK('MODULE2_SUB1',1,ZHOOK_HANDLE)

END SUBROUTINE MODULE2_SUB3

SUBROUTINE MODULE2_SUB4(A)

USE YOMHOOK,    ONLY: LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE

REAL, INTENT(INOUT) :: A

IF (LHOOK) CALL DR_HOOK('MODULE2_SUB1',0,ZHOOK_HANDLE)

IF (LHOOK) CALL DR_HOOK('MODULE2_SUB1',1,ZHOOK_HANDLE)

END SUBROUTINE MODULE2_SUB4
END MODULE MODE_MODULE2
