PROGRAM MAIN_TURB


!USE YOMTURB
USE YOMDATA
!USE MODI_TURB

USE MODE_SHUMAN_PHY, ONLY: MZF_PHY,MXF_PHY,MYF_PHY
USE YOMHOOK ,   ONLY: LHOOK, DR_HOOK, JPHOOK
!
USE MODD_BUDGET,     ONLY:  NBUDGET_U,  NBUDGET_V,  NBUDGET_W,  NBUDGET_TH, NBUDGET_RV, NBUDGET_RC, &
                            NBUDGET_RI, NBUDGET_SV1, NBUDGET_RG, NBUDGET_RH, NBUDGET_RR, NBUDGET_RS, &
                            TBUDGETDATA_PTR, TBUDGETCONF_T
USE MODD_CST,        ONLY: CST_t
USE MODD_CTURB,      ONLY: CSTURB_t
USE MODD_DIMPHYEX,   ONLY: DIMPHYEX_t
USE MODD_FIELD,      ONLY: TFIELDMETADATA, TYPEREAL
USE MODD_IO,         ONLY: TFILEDATA
USE MODD_LES,        ONLY: TLES_t
USE MODD_PARAMETERS, ONLY: JPVEXT_TURB, XUNDEF
USE MODD_TURB_n,     ONLY: TURB_t
USE MODD_NEB_n,      ONLY: NEB_t
!
USE MODE_BL89,                ONLY: BL89
USE MODE_EMOIST,              ONLY: EMOIST
USE MODE_ETHETA,              ONLY: ETHETA
USE MODE_GRADIENT_U_PHY,      ONLY: GZ_U_UW_PHY
USE MODE_GRADIENT_V_PHY,      ONLY: GZ_V_VW_PHY
USE MODE_GRADIENT_W_PHY,      ONLY: GZ_W_M_PHY
USE MODE_GRADIENT_M_PHY,      ONLY: GZ_M_W_PHY
USE MODE_IBM_MIXINGLENGTH,    ONLY: IBM_MIXINGLENGTH
USE MODE_IO_FIELD_WRITE_PHY,      ONLY: IO_FIELD_WRITE_PHY
!#USE MODE_RMC01,               ONLY: RMC01
!#USE MODE_ROTATE_WIND,         ONLY: ROTATE_WIND, UPDATE_ROTATE_WIND
USE MODE_SBL_PHY,             ONLY: LMO
USE MODE_SOURCES_NEG_CORRECT, ONLY: SOURCES_NEG_CORRECT_PHY
!#USE MODE_TM06,                ONLY: TM06
USE MODE_TKE_EPS_SOURCES,     ONLY: TKE_EPS_SOURCES
!#USE MODE_TURB_HOR_SPLT,       ONLY: TURB_HOR_SPLT
USE MODE_TURB_VER,            ONLY: TURB_VER
!#USE MODE_UPDATE_LM,           ONLY: UPDATE_LM
!#USE MODE_MSG,                 ONLY: PRINT_MSG, NVERB_FATAL
!
USE MODI_LES_MEAN_SUBGRID_PHY
USE MODI_SECOND_MNH,          ONLY: SECOND_MNH

USE UTIL_CSTURB_T_MOD
USE UTIL_TURB_T_MOD
USE UTIL_NEB_T_MOD
USE UTIL_CST_T_MOD
USE UTIL_DIMPHYEX_T_MOD
USE UTIL_TLES_T_MOD
USE UTIL_TFILEDATA_MOD

USE XRD_GETOPTIONS
USE XRD_UNIX_ENV

#include "fxtran_acdc_stack.h"

USE FXTRAN_ACDC_STACK_MOD

USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : STDOUT => OUTPUT_UNIT



!
! These macro are handled by pft_tool.py --craybyPassDOCONCURRENT applied on Cray Rules
#ifdef MNH_COMPILER_CCE
!$mnh_undef(LOOP)
!$mnh_undef(OPENACC)
#endif
!
IMPLICIT NONE
!
!
!*      0.1  declarations of arguments
!
!
!
TYPE(DIMPHYEX_t)   :: D             ! PHYEX variables dimensions structure
TYPE(CST_t)   :: CST           ! modd_cst general constant structure
TYPE(CSTURB_t)   :: CSTURB        ! modd_csturb turb constant structure
!TYPE(TBUDGETCONF_t)   :: BUCONF        ! budget structure
TYPE(TURB_t)   :: TURBN         ! modn_turbn (turb namelist) structure
TYPE(NEB_t)   :: NEBN          ! modd_nebn structure
TYPE(TLES_t)   :: TLES          ! modd_les structure

TYPE(TFILEDATA) ::  TPFILE       ! Output file



! integer and logical
INTEGER(KIND=JPIM)   :: KGRADIENTSLEO ! Number of stored horizontal gradients for Moeng scheme
INTEGER(KIND=JPIM)   :: KGRADIENTSGOG ! Number of stored horizontal gradients for Goger scheme
INTEGER(KIND=JPIM)   :: KRR           ! number of moist var.
INTEGER(KIND=JPIM)   :: KRRL          ! number of liquid water var.
INTEGER(KIND=JPIM)   :: KRRI          ! number of ice water var.
INTEGER(KIND=JPIM)   :: KSV, KSV_LGBEG, KSV_LGEND ! number of scalar variables
INTEGER(KIND=JPIM)   :: KSV_LIMA_NR,KSV_LIMA_NS,KSV_LIMA_NG,KSV_LIMA_NH
CHARACTER(LEN=4),DIMENSION(2) :: HLBCX, HLBCY  ! X- and Y-direc LBC
INTEGER(KIND=JPIM)   :: KSPLIT        ! number of time-splitting
INTEGER(KIND=JPIM)   ::  KHALO        ! Size of the halo for parallel distribution
INTEGER(KIND=JPIM)   :: KBUDGETS
INTEGER(KIND=JPIM)  :: IGPBLKS
!TYPE(TBUDGETDATA_PTR), DIMENSION(KBUDGETS) :: TBUDGETS
INTEGER(KIND=JPIM)   :: IIJB,IIJE,IKB,IKE      ! index value for the
INTEGER(KIND=JPIM)   :: IKT,IKA,IKU  ! array size in k direction
INTEGER(KIND=JPIM)   :: IKL
INTEGER(KIND=JPIM)   :: IKTB,IKTE    ! start, end of k loops in physical domain
INTEGER(KIND=JPIM)   :: JRR,JK,JSV   ! loop counters
INTEGER(KIND=JPIM)   :: JIJ          ! loop counters
INTEGER(KIND=JPIM)   :: ISV


LOGICAL   :: OCLOUDMODIFLM ! cloud mixing length modifications
LOGICAL   ::  OCOMPUTE_SRC ! flag to define dimensions of SIGS and SRCT variables
LOGICAL   ::  OOCEAN       ! switch for Ocean model version
LOGICAL   ::  ODEEPOC      ! activates sfc forcing for ideal ocean deep conv
LOGICAL   ::  OFLYER       ! MesoNH flyer diagnostic
LOGICAL   ::  OFLAT        ! Logical for zero ororography
LOGICAL   ::  OCOUPLES     ! switch to activate atmos-ocean LES version 
LOGICAL   ::  OBLOWSNOW    ! switch to activate pronostic blowing snow
LOGICAL   ::  ODIAG_IN_RUN ! switch to activate online diagnostics (mesonh)
LOGICAL   ::  OIBM         ! switch to modity mixing length near building with IBM
CHARACTER(LEN=4)  ::  HTURBLEN_CL  ! kind of cloud mixing length
CHARACTER (LEN=4) ::  HCLOUD       ! Kind of microphysical scheme
CHARACTER (LEN=4) ::  HELEC        ! Kind of cloud electricity scheme
REAL(KIND=JPRB) ::  PRSNOW       ! Ratio for diffusion coeff. scalar (blowing snow)
REAL(KIND=JPRB) ::  PTSTEP       ! timestep
LOGICAL   :: ONOMIXLG          ! to use turbulence for lagrangian variables (modd_conf)
LOGICAL   :: O2D               ! Logical for 2D model version (modd_conf)
LOGICAL   :: GOCEAN !Intermediate variable used to work around a Cray compiler bug (CCE 13.0.0)
LOGICAL   :: GTURBLEN_BL89_TURBLEN_RM17_TURBLEN_HM21_ORMC01
LOGICAL   :: ODZ
LOGICAL   :: GZD


REAL(KIND=JPRB) ::  PCEI_MIN ! minimum threshold for the instability index CEI
REAL(KIND=JPRB) ::  PCEI_MAX ! maximum threshold for the instability index CEI
REAL(KIND=JPRB) ::  PCOEF_AMPL_SAT ! saturation of the amplification coefficient

!REAL(KIND=JPRB), POINTER, DIMENSION(:, :) :: ZZLBCX
!REAL(KIND=JPRB), POINTER, DIMENSION(:, :) :: ZZLBCY
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZDXX
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZDYY
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZDZZ
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZDZX
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZDZY
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZZZ
REAL(KIND=JPRB), POINTER, DIMENSION(:, :) :: ZZDIRCOSXW
REAL(KIND=JPRB), POINTER, DIMENSION(:, :) :: ZZDIRCOSYW
REAL(KIND=JPRB), POINTER, DIMENSION(:, :) :: ZZDIRCOSZW
REAL(KIND=JPRB), POINTER, DIMENSION(:, :) :: ZZCOSSLOPE
REAL(KIND=JPRB), POINTER, DIMENSION(:, :) :: ZZSINSLOPE
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZRHODJ
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZTHVREF
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :, :) :: ZZHGRADLEO
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :, :) :: ZZHGRADGOG
REAL(KIND=JPRB), POINTER, DIMENSION(:, :) :: ZZZS
REAL(KIND=JPRB), POINTER, DIMENSION(:, :) :: ZZSFTH
REAL(KIND=JPRB), POINTER, DIMENSION(:, :) :: ZZSFRV
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZSFSV
REAL(KIND=JPRB), POINTER, DIMENSION(:, :) :: ZZSFU
REAL(KIND=JPRB), POINTER, DIMENSION(:, :) :: ZZSFV
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZPABST
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZUT
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZVT
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZWT
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZTKET
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :, :) :: ZZSVT
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZSRCT
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZLENGTHM
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZLENGTHH
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZFMOIST
REAL(KIND=JPRB), POINTER, DIMENSION(:, :) :: ZZBL_DEPTH
REAL(KIND=JPRB), POINTER, DIMENSION(:, :) :: ZZSBL_DEPTH
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZCEI
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZTHLT
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :, :) :: ZZRT
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZRUS
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZRVS
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZRWS
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZRTHLS
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :, :) :: ZZRRS
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :, :) :: ZZRSVS
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZRTKES
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZSIGS
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZFLXZTHVMF
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZFLXZUMF
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZFLXZVMF
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZWTH
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZWRC
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :, :) :: ZZWSV
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZDP
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZTP
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZTDIFF
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZTDISS
!REAL(KIND=JPRB), POINTER, DIMENSION(:, :) :: ZZBUDGETS
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZEDR
!REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZLEM
!REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZRTKEMS
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZDPMF
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZTPMF
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZDRUS_TURB
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZDRVS_TURB
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZDRTHLS_TURB
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZDRRTS_TURB
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :, :) :: ZZDRSVS_TURB
!REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZTR
!REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZDISS
!REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZIBM_LS
!REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZIBM_XMUT
!REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZCURRENT_TKE_DISS
!REAL(KIND=JPRB), POINTER, DIMENSION(:, :) :: ZZSSTFL
!REAL(KIND=JPRB), POINTER, DIMENSION(:, :) :: ZZSSTFL_C
!REAL(KIND=JPRB), POINTER, DIMENSION(:, :) :: ZZSSRFL_C
!REAL(KIND=JPRB), POINTER, DIMENSION(:, :) :: ZZSSUFL_C
!REAL(KIND=JPRB), POINTER, DIMENSION(:, :) :: ZZSSVFL_C
!REAL(KIND=JPRB), POINTER, DIMENSION(:, :) :: ZZSSUFL
!REAL(KIND=JPRB), POINTER, DIMENSION(:, :) :: ZZSSVFL

INTEGER(KIND=JPIM) :: ILUN

#include "turb.intfb.h"

INTEGER(KIND=JPIM) :: JLON, JBLK
INTEGER(KIND=JPIM) :: ILUNCI, ILUNFI, ILUNFO, IOUT
INTEGER(KIND=JPIM) :: NPROMA, NGPBLKS,KLEV,KLON,KGPBLKS
CHARACTER (LEN=128) :: CLOUT
CHARACTER (LEN=128) :: CLCASE_IN
CHARACTER (LEN=128) :: CLCASE_OUT
TYPE (DD12), POINTER :: YLD
LOGICAL :: LLVERBOSE, LLDIFF
INTEGER(KIND=JPIM), POINTER :: IBLOCKLIST (:)
TYPE(FXTRAN_ACDC_STACK) :: YLSTACK
TYPE(FXTRAN_ACDC_STACK) :: YLOFFSET
INTEGER(KIND=JPIM) :: ISIZE4, ISIZE8
CHARACTER*64 :: CLMETHOD
INTEGER(KIND=JPIM) :: ITIME, NTIME
LOGICAL :: LLSAVE, LLEXIST
REAL(KIND=JPRB) :: TSC, TEC, TSD, TED, ZTC, ZTD

#ifdef ARCH
CHARACTER (LEN=*), PARAMETER :: CLARCH = ARCH
#else
CHARACTER (LEN=*), PARAMETER :: CLARCH = 'unkwown'
#endif

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE


IF (LHOOK) CALL DR_HOOK ('MAIN_TURB', 0, ZHOOK_HANDLE)

YLD => NULL ()

CALL INITOPTIONS

NPROMA  = 0; CALL GETOPTION ("--nproma",  NPROMA)
NGPBLKS = 0; CALL GETOPTION ("--ngpblks", NGPBLKS)

CALL GETOPTION ("--case-in", CLCASE_IN, MND=.TRUE.)
CLCASE_OUT = ''; CALL GETOPTION ("--case-out", CLCASE_OUT)

CALL GETOPTION ("--verbose", LLVERBOSE)
CALL GETOPTION ("--diff", LLDIFF)
#ifdef PARKIND1_SINGLE
ISIZE4 = 80;
ISIZE8 = 10;
#else
ISIZE4 = 10;
ISIZE8 = 80;
#endif
CALL GETOPTION ("--stack-size-4", ISIZE4)
CALL GETOPTION ("--stack-size-8", ISIZE8)
NTIME = 1; CALL GETOPTION ("--times", NTIME)

CLMETHOD = 'openmp'; CALL GETOPTION ("--method", CLMETHOD)

IBLOCKLIST => NULL ()
CALL GETOPTION ("--block-list", IBLOCKLIST)

LLSAVE = CLCASE_OUT /= ''

IF (LLSAVE) THEN
  CALL XRD_MKDIR (TRIM (CLCASE_OUT))
ENDIF

CLOUT = '-'; CALL GETOPTION ("--out", CLOUT)

CALL CHECKOPTIONS

HLBCX(1)="CYCL"
HLBCX(2)="CYCL"
HLBCY(1)="CYCL"
HLBCY(2)="CYCL"
HTURBLEN_CL="DELT"
HCLOUD="ICE3"
HELEC="NONE"
CALL LOADALL

IF (LLVERBOSE) THEN
WRITE (0, *) " NPROMA = ", NPROMA, " NGPBLKS = ", NGPBLKS, " KLEV = ", KLEV
WRITE (0, *) " ISIZE4 = ", ISIZE4, " ISIZE8 = ", ISIZE8, " NTIME = ", NTIME
ENDIF

IF (LLSAVE) THEN
  CALL SAVEIALL
ENDIF


CALL GET_TIME (TSD)

!$ACC DATA COPY ( ZZDXX, ZZDYY, ZZDZZ, ZZDZX, ZZDZY, ZZZZ, ZZDIRCOSXW, &
!$ACC& ZZDIRCOSYW, ZZDIRCOSZW, ZZCOSSLOPE, ZZSINSLOPE, ZZRHODJ,        &
!$ACC& ZZTHVREF, ZZHGRADLEO, ZZHGRADGOG, ZZZS, ZZSFTH, ZZSFRV, ZZSFSV, &
!$ACC& ZZSFU, ZZSFV, ZZPABST, ZZUT, ZZVT, ZZWT, ZZTKET, ZZSVT, ZZSRCT, &
!$ACC& ZZLENGTHM, ZZLENGTHH, ZZFMOIST, ZZBL_DEPTH, ZZSBL_DEPTH, ZZCEI, &
!$ACC& ZZTHLT, ZZRT, ZZRUS, ZZRVS, ZZRWS, ZZRTHLS, ZZRRS, ZZRSVS,      &
!$ACC& ZZRTKES, ZZSIGS, ZZFLXZTHVMF, ZZFLXZUMF, ZZFLXZVMF, ZZWTH,      &
!$ACC& ZZWSV, ZZDP, ZZTP, ZZTDIFF, ZZTDISS, ZZEDR, ZZDPMF, ZZTPMF,     &
!$ACC& ZZDRUS_TURB, ZZDRVS_TURB, ZZDRTHLS_TURB, ZZDRRTS_TURB,          &
!$ACC& ZZDRSVS_TURB) IF (TRIM (CLMETHOD) == 'openaccsinglecolumn')

IF (TRIM (CLMETHOD) == 'openaccsinglecolumn') THEN
  CALL ACDC_COPY(D)
  CALL ACDC_COPY(CST)
  CALL ACDC_COPY(CSTURB)
  !CALLACDC_COPYD(BUCONF, ILUNCI)
  CALL ACDC_COPY(TURBN)
  CALL ACDC_COPY(NEBN)
  CALL ACDC_COPY(TLES)
  CALL ACDC_COPY(TPFILE)
  CALL YFXTRAN_ACDC_STACK%INIT(NPROMA,KLEV,NGPBLKS,ISIZE4,ISIZE8)
ENDIF


CALL GET_TIME (TSC)

DO ITIME = 1, NTIME

  IF (TRIM (CLMETHOD) == 'openmp') THEN

!$OMP PARALLEL DO PRIVATE (JBLK) 
    DO JBLK = 1, NGPBLKS

CALL TURB(CST,CSTURB,TURBN,NEBN,D,TLES,            &                 
        & KRR,KRRL,KRRI,HLBCX,HLBCY,KGRADIENTSLEO,              &                 
        & KGRADIENTSGOG,KHALO,                                  &                 
        & KSPLIT, OCLOUDMODIFLM, KSV,KSV_LGBEG,KSV_LGEND,       &                 
        & KSV_LIMA_NR, KSV_LIMA_NS, KSV_LIMA_NG, KSV_LIMA_NH,   &                 
        & O2D,ONOMIXLG,OFLAT,OCOUPLES,OBLOWSNOW,OIBM,OFLYER,    &                 
        & OCOMPUTE_SRC, PRSNOW,                                 & 
        & OOCEAN,ODEEPOC,ODIAG_IN_RUN,                          &
        & HTURBLEN_CL,HCLOUD,HELEC,                             &
        & PTSTEP,TPFILE,                                        &
        & ZZDXX(:, :, JBLK), ZZDYY(:, :, JBLK), ZZDZZ(:, :, JBLK),  &
        & ZZDZX(:, :, JBLK), ZZDZY(:, :, JBLK), ZZZZ(:, :, JBLK),  &
        & ZZDIRCOSXW(:, JBLK), ZZDIRCOSYW(:, JBLK),  &
        & ZZDIRCOSZW(:, JBLK), ZZCOSSLOPE(:, JBLK),  &
        & ZZSINSLOPE(:, JBLK), ZZRHODJ(:, :, JBLK),  &
        & ZZTHVREF(:, :, JBLK), ZZHGRADLEO(:, :, :, JBLK),  &
        & ZZHGRADGOG(:, :, :, JBLK), ZZZS(:, JBLK), ZZSFTH(:, JBLK),  &
        & ZZSFRV(:, JBLK), ZZSFSV(:, :, JBLK), ZZSFU(:, JBLK),  &
        & ZZSFV(:, JBLK), ZZPABST(:, :, JBLK), ZZUT(:, :, JBLK),  &
        & ZZVT(:, :, JBLK), ZZWT(:, :, JBLK), ZZTKET(:, :, JBLK),  &
        & ZZSVT(:, :, :, JBLK), ZZSRCT(:, :, JBLK),  &
        & ZZLENGTHM(:, :, JBLK), ZZLENGTHH(:, :, JBLK),  &
        & ZZFMOIST(:, :, JBLK), ZZBL_DEPTH(:, JBLK),  &
        & ZZSBL_DEPTH(:, JBLK), ZZCEI(:, :, JBLK),  &
        & PCEI_MIN, PCEI_MAX, PCOEF_AMPL_SAT, &
        & ZZTHLT(:, :, JBLK), ZZRT(:, :, :, JBLK), ZZRUS(:, :, JBLK),  &
        & ZZRVS(:, :, JBLK), ZZRWS(:, :, JBLK), ZZRTHLS(:, :, JBLK),  &
        & ZZRRS(:, :, :, JBLK), ZZRSVS(:, :, :, JBLK),  &
        & ZZRTKES(:, :, JBLK), ZZSIGS(:, :, JBLK),  &
        & ZZFLXZTHVMF(:, :, JBLK), ZZFLXZUMF(:, :, JBLK),  &
        & ZZFLXZVMF(:, :, JBLK), ZZWTH(:, :, JBLK),  &
        & ZZWRC(:, :, JBLK), ZZWSV(:, :, :, JBLK), ZZDP(:, :, JBLK),  &
        & ZZTP(:, :, JBLK), ZZTDIFF(:, :, JBLK), ZZTDISS(:, :, JBLK),  &
        & KBUDGETS, &
        & PEDR=ZZEDR(:, :, JBLK), &
        & PDPMF=ZZDPMF(:, :, JBLK),  &
        & PTPMF=ZZTPMF(:, :, JBLK), PDRUS_TURB=ZZDRUS_TURB(:, :, JBLK),  &
        & PDRVS_TURB=ZZDRVS_TURB(:, :, JBLK), PDRTHLS_TURB=ZZDRTHLS_TURB(:, :, JBLK),  &
        & PDRRTS_TURB=ZZDRRTS_TURB(:, :, JBLK), PDRSVS_TURB=ZZDRSVS_TURB(:, :, :, JBLK))





!        & PDXX(:, :, JBLK),  &
!        & PDYY(:, :, JBLK), PDZZ(:, :, JBLK), PDZX(:, :, JBLK),  &
!        & PDZY(:, :, JBLK), PZZ(:, :, JBLK), PDIRCOSXW(:, JBLK),  &
!        & PDIRCOSYW(:, JBLK), PDIRCOSZW(:, JBLK), PCOSSLOPE(:, JBLK),  &
!        & PSINSLOPE(:, JBLK), PRHODJ(:, :, JBLK),  &
!        & PTHVREF(:, :, JBLK), PHGRADLEO(:, :, :, JBLK),  &
!        & PHGRADGOG(:, :, :, JBLK), PZS(:, JBLK), PSFTH(:, JBLK),  &
!        & PSFRV(:, JBLK), PSFSV(:, :, JBLK), PSFU(:, JBLK),  &
!        & PSFV(:, JBLK), PPABST(:, :, JBLK), PUT(:, :, JBLK),  &
!        & PVT(:, :, JBLK), PWT(:, :, JBLK), PTKET(:, :, JBLK),  &
!        & PSVT(:, :, :, JBLK), PSRCT(:, :, JBLK),  &
!        & PLENGTHM(:, :, JBLK), PLENGTHH(:, :, JBLK),  &
!        & MFMOIST(:, :, JBLK), PBL_DEPTH(:, JBLK),  &
!        & PSBL_DEPTH(:, JBLK), PCEI(:, :, JBLK), PTHLT(:, :, JBLK),  &
!        & PRT(:, :, :, JBLK), PRUS(:, :, JBLK), PRVS(:, :, JBLK),  &
!        & PRWS(:, :, JBLK), PRTHLS(:, :, JBLK), PRRS(:, :, :, JBLK),  &
!        & PRSVS(:, :, :, JBLK), PRTKES(:, :, JBLK),  &
!        & PSIGS(:, :, JBLK), PFLXZTHVMF(:, :, JBLK),  &
!        & PFLXZUMF(:, :, JBLK), PFLXZVMF(:, :, JBLK),  &
!        & PWTH(:, :, JBLK), PWRC(:, :, JBLK), PWSV(:, :, :, JBLK),  &
!        & PDP(:, :, JBLK), PTP(:, :, JBLK), PTDIFF(:, :, JBLK),  &
!        & PTDISS(:, :, JBLK), TBUDGETS(:, JBLK), KBUDGETS=KBUDGETS, &
!        & PEDR=PEDR(:, :, JBLK),  &
!        & PDPMF=PDPMF(:, :, JBLK),  &
!        & PTPMF=PTPMF(:, :, JBLK), PDRUS_TURB=PDRUS_TURB(:, :, JBLK),  &
!        & PDRVS_TURB=PDRVS_TURB(:, :, JBLK), PDRTHLS_TURB=PDRTHLS_TURB(:, :, JBLK),  &
!        & PDRRTS_TURB=PDRRTS_TURB(:, :, JBLK), PDRSVS_TURB=PDRSVS_TURB(:, :, :, JBLK))
    ENDDO !jblk
  ELSEIF (TRIM (CLMETHOD) == 'openmpsinglecolumn') THEN

!$OMP PARALLEL DO PRIVATE (JBLK, JLON, YLSTACK) FIRSTPRIVATE(D) COLLAPSE(2)
    DO JBLK = 1, NGPBLKS
      DO JLON = 1,NPROMA
        D%NIJB=JLON
        D%NIJE=JLON
        D%NIB=JLON
        D%NIE=JLON
        YLSTACK%L8 = fxtran_acdc_stack_l8 (YFXTRAN_ACDC_STACK, JBLK, NGPBLKS)
        YLSTACK%U8 = fxtran_acdc_stack_u8 (YFXTRAN_ACDC_STACK, JBLK, NGPBLKS)
        YLSTACK%L4 = fxtran_acdc_stack_l4 (YFXTRAN_ACDC_STACK, JBLK, NGPBLKS)
        YLSTACK%U4 = fxtran_acdc_stack_u4 (YFXTRAN_ACDC_STACK, JBLK, NGPBLKS)

!#      CALL TURB_OPENACC(CST,CSTURB,TURBN,NEBN,D,TLES,            &                 
!#              & KRR,KRRL,KRRI,HLBCX,HLBCY,KGRADIENTSLEO,              &                 
!#              & KGRADIENTSGOG,KHALO,                                  &                 
!#              & KSPLIT, OCLOUDMODIFLM, KSV,KSV_LGBEG,KSV_LGEND,       &                 
!#              & KSV_LIMA_NR, KSV_LIMA_NS, KSV_LIMA_NG, KSV_LIMA_NH,   &                 
!#              & O2D,ONOMIXLG,OFLAT,OCOUPLES,OBLOWSNOW,OIBM,OFLYER,    &                 
!#              & OCOMPUTE_SRC, PRSNOW,                                 & 
!#              & OOCEAN,ODEEPOC,ODIAG_IN_RUN,                          &
!#              & HTURBLEN_CL,HCLOUD,HELEC,                             &
!#              & PTSTEP,TPFILE,                                        &
!#              & ZZDXX(:, :, JBLK), ZZDYY(:, :, JBLK), ZZDZZ(:, :, JBLK),  &
!#              & ZZDZX(:, :, JBLK), ZZDZY(:, :, JBLK), ZZZZ(:, :, JBLK),  &
!#              & ZZDIRCOSXW(:, JBLK), ZZDIRCOSYW(:, JBLK),  &
!#              & ZZDIRCOSZW(:, JBLK), ZZCOSSLOPE(:, JBLK),  &
!#              & ZZSINSLOPE(:, JBLK), ZZRHODJ(:, :, JBLK),  &
!#              & ZZTHVREF(:, :, JBLK), ZZHGRADLEO(:, :, :, JBLK),  &
!#              & ZZHGRADGOG(:, :, :, JBLK), ZZZS(:, JBLK), ZZSFTH(:, JBLK),  &
!#              & ZZSFRV(:, JBLK), ZZSFSV(:, :, JBLK), ZZSFU(:, JBLK),  &
!#              & ZZSFV(:, JBLK), ZZPABST(:, :, JBLK), ZZUT(:, :, JBLK),  &
!#              & ZZVT(:, :, JBLK), ZZWT(:, :, JBLK), ZZTKET(:, :, JBLK),  &
!#              & ZZSVT(:, :, :, JBLK), ZZSRCT(:, :, JBLK),  &
!#              & ZZLENGTHM(:, :, JBLK), ZZLENGTHH(:, :, JBLK),  &
!#              & ZZFMOIST(:, :, JBLK), ZZBL_DEPTH(:, JBLK),  &
!#              & ZZSBL_DEPTH(:, JBLK), ZZCEI(:, :, JBLK),  &
!#              & PCEI_MIN, PCEI_MAX, PCOEF_AMPL_SAT, &
!#              & ZZTHLT(:, :, JBLK), ZZRT(:, :, :, JBLK), ZZRUS(:, :, JBLK),  &
!#              & ZZRVS(:, :, JBLK), ZZRWS(:, :, JBLK), ZZRTHLS(:, :, JBLK),  &
!#              & ZZRRS(:, :, :, JBLK), ZZRSVS(:, :, :, JBLK),  &
!#              & ZZRTKES(:, :, JBLK), ZZSIGS(:, :, JBLK),  &
!#              & ZZFLXZTHVMF(:, :, JBLK), ZZFLXZUMF(:, :, JBLK),  &
!#              & ZZFLXZVMF(:, :, JBLK), ZZWTH(:, :, JBLK),  &
!#              & ZZWRC(:, :, JBLK), ZZWSV(:, :, :, JBLK), ZZDP(:, :, JBLK),  &
!#              & ZZTP(:, :, JBLK), ZZTDIFF(:, :, JBLK), ZZTDISS(:, :, JBLK),  &
!#              & KBUDGETS, &
!#              & PEDR=ZZEDR(:, :, JBLK), &
!#              & PDPMF=ZZDPMF(:, :, JBLK),  &
!#              & PTPMF=ZZTPMF(:, :, JBLK), PDRUS_TURB=ZZDRUS_TURB(:, :, JBLK),  &
!#              & PDRVS_TURB=ZZDRVS_TURB(:, :, JBLK), PDRTHLS_TURB=ZZDRTHLS_TURB(:, :, JBLK),  &
!#              & PDRRTS_TURB=ZZDRRTS_TURB(:, :, JBLK), PDRSVS_TURB=ZZDRSVS_TURB(:, :, :, JBLK), & 
!#              & YDSTACK=YLSTACK)
      ENDDO !jlon
    ENDDO !jblk
  ENDIF !method omp/acc 
ENDDO !time

CALL GET_TIME (TEC)

IF (TRIM (CLMETHOD) == 'openaccsinglecolumn') THEN
  CALL ACDC_COPY(D)
  CALL ACDC_COPY(CST)
  CALL ACDC_COPY(CSTURB)
  !CALLACDC_COPYD(BUCONF, ILUNCI)
  CALL ACDC_COPY(TURBN)
  CALL ACDC_COPY(NEBN)
  CALL ACDC_COPY(TLES)
  CALL ACDC_COPY(TPFILE)
ENDIF

!$ACC END DATA

CALL GET_TIME (TED)

ZTC = TEC - TSC
ZTD = TED - TSD

LLEXIST = .FALSE.

IF (CLOUT == '-') THEN
  IOUT = STDOUT
ELSE
  IOUT = 77
  INQUIRE (FILE=TRIM (CLOUT), EXIST=LLEXIST)
  IF (LLEXIST) THEN
    OPEN (IOUT, FILE=TRIM (CLOUT), FORM='FORMATTED', STATUS='OLD', POSITION='APPEND')
  ELSE
    OPEN (IOUT, FILE=TRIM (CLOUT), FORM='FORMATTED', STATUS='NEW')
  ENDIF
ENDIF

IF (.NOT. LLEXIST) &
WRITE (IOUT, '(A16,";",A32,";",A8,";",A8,";",A8,4(";",A20))') &
              & "CLARCH", "CLMETHOD", "NPROMA", "NGPBLKS", "NTIME", &
              & "ZTCTOT", "ZTC", "ZTDTOT", "ZTD"

WRITE (IOUT, '(A16,";",A32,";",I8,";",I8,";",I8,4(";",E20.10))') &
              & CLARCH,  TRIM (CLMETHOD), NPROMA, NGPBLKS, NTIME, &
              & ZTC, ZTC / REAL(NPROMA*NGPBLKS*NTIME, 8), &
              & ZTD, ZTD / REAL(NPROMA*NGPBLKS*NTIME, 8)

IF (IOUT /= STDOUT) THEN
  CLOSE (IOUT)
ENDIF


IF (LLDIFF) THEN
  CALL DIFFALL
ENDIF

IF (LLSAVE) THEN
  CALL SAVEOALL
ENDIF
WRITE (0, *) __FILE__, ':', __LINE__

IF (LHOOK) CALL DR_HOOK ('MAIN_TURB', 1, ZHOOK_HANDLE)

CONTAINS



SUBROUTINE LOADALL

ILUNCI = 77
ILUNFI = 78

OPEN (ILUNCI, NAME=TRIM (CLCASE_IN)//'/TURB.CONST.dat', FORM='UNFORMATTED')
OPEN (ILUNFI, NAME=TRIM (CLCASE_IN)//'/TURB.IN.dat',    FORM='UNFORMATTED')



CALL ACDC_LOAD(D, ILUNCI)
CALL ACDC_LOAD(CST, ILUNCI)
CALL ACDC_LOAD(CSTURB, ILUNCI)
!CALLACDC_ LOAD(BUCONF, ILUNCI)
CALL ACDC_LOAD(TURBN, ILUNCI)
CALL ACDC_LOAD(NEBN, ILUNCI)
CALL ACDC_LOAD(TLES, ILUNCI)
CALL ACDC_LOAD(TPFILE, ILUNCI)
!CALL LOAD(TBUDGETS, ILUNCI)
CALL LOAD(ILUNCI, KGRADIENTSLEO)
CALL LOAD(ILUNCI, KGRADIENTSGOG)
CALL LOAD(ILUNCI, KRR)
CALL LOAD(ILUNCI, KRRL)
CALL LOAD(ILUNCI, KRRI)
CALL LOAD(ILUNCI, KSV)
CALL LOAD(ILUNCI, KSV_LGBEG) 
CALL LOAD(ILUNCI, KSV_LGEND)
CALL LOAD(ILUNCI, KSV_LIMA_NR)
CALL LOAD(ILUNCI, KSV_LIMA_NS)
CALL LOAD(ILUNCI, KSV_LIMA_NG)
CALL LOAD(ILUNCI, KSV_LIMA_NH)
!CALL LOAD(ILUNCI, HLBCX)
!CALL LOAD(ILUNCI, HLBCY)
CALL LOAD(ILUNCI, KSPLIT) 
CALL LOAD(ILUNCI, OCLOUDMODIFLM)
CALL LOAD(ILUNCI, KHALO)
CALL LOAD(ILUNCI, OCOMPUTE_SRC)
CALL LOAD(ILUNCI, OOCEAN)
CALL LOAD(ILUNCI, ODEEPOC)
CALL LOAD(ILUNCI, OFLYER)
CALL LOAD(ILUNCI, OFLAT)
CALL LOAD(ILUNCI, OCOUPLES)
CALL LOAD(ILUNCI, OBLOWSNOW)
CALL LOAD(ILUNCI, ODIAG_IN_RUN)
CALL LOAD(ILUNCI, OIBM)
!CALL LOAD(ILUNCI, HTURBLEN_CL)
!CALL LOAD(ILUNCI, HCLOUD)
!CALL LOAD(ILUNCI, HELEC)
CALL LOAD(ILUNCI, PRSNOW)
CALL LOAD(ILUNCI, PTSTEP)
CALL LOAD(ILUNCI, PCEI_MIN) 
CALL LOAD(ILUNCI, PCEI_MAX)
CALL LOAD(ILUNCI, PCOEF_AMPL_SAT)
!TYPE(TBUDGETDATA_PTR), DIMENSION(KBUDGETS), INTENT(INOUT) :: TBUDGETS
CALL LOAD(ILUNCI, KBUDGETS)
CALL LOAD(ILUNCI, ONOMIXLG)
CALL LOAD(ILUNCI, O2D)
CALL LOAD (ILUNCI, IGPBLKS)


KLON=D%NIJE-D%NIJB+1
KGPBLKS=IGPBLKS
IF (NPROMA == 0) NPROMA = KLON
IF (NGPBLKS == 0) THEN
  IF (ASSOCIATED (IBLOCKLIST)) THEN
    NGPBLKS = SIZE (IBLOCKLIST)
  ELSE
    NGPBLKS = KGPBLKS
  ENDIF
ENDIF
KLEV=D%NKT !D%NKT

IF ((NPROMA /= KLON) .OR. (NGPBLKS /= KGPBLKS) .OR. ASSOCIATED (IBLOCKLIST)) THEN

  ALLOCATE (YLD)

  IF (ASSOCIATED (IBLOCKLIST)) THEN
    CALL YLD%INIT ([KLON, KGPBLKS], [NPROMA, NGPBLKS], IBLOCKLIST)
  ELSE
    CALL YLD%INIT ([KLON, KGPBLKS], [NPROMA, NGPBLKS])
  ENDIF

  NPROMA = YLD%IPROMA2
  NGPBLKS = YLD%IGPBLKS2

ENDIF

KLON = NPROMA
KGPBLKS = NGPBLKS
D%NIB=1
D%NIE=KLON
D%NIBC=1
D%NIEC=KLON
D%NIJB=1
D%NIJE=KLON
D%NIBC=1
D%NIEC=KLON
D%NIT=KLON
D%NIJT=KLON



!CALL LOAD(ILUNFI, ZZLBCX, YDD=YLD)
!CALL LOAD(ILUNFI, ZZLBCY, YDD=YLD)
CALL LOAD(ILUNFI, ZZDXX, YDD=YLD)
CALL LOAD(ILUNFI, ZZDYY, YDD=YLD)
CALL LOAD(ILUNFI, ZZDZZ, YDD=YLD)
CALL LOAD(ILUNFI, ZZDZX, YDD=YLD)
CALL LOAD(ILUNFI, ZZDZY, YDD=YLD)
CALL LOAD(ILUNFI, ZZZZ, YDD=YLD)
CALL LOAD(ILUNFI, ZZDIRCOSXW, YDD=YLD)
CALL LOAD(ILUNFI, ZZDIRCOSYW, YDD=YLD)
CALL LOAD(ILUNFI, ZZDIRCOSZW, YDD=YLD)
CALL LOAD(ILUNFI, ZZCOSSLOPE, YDD=YLD)
CALL LOAD(ILUNFI, ZZSINSLOPE, YDD=YLD)
CALL LOAD(ILUNFI, ZZRHODJ, YDD=YLD)
CALL LOAD(ILUNFI, ZZTHVREF, YDD=YLD)
CALL LOAD(ILUNFI, ZZHGRADLEO, YDD=YLD)
CALL LOAD(ILUNFI, ZZHGRADGOG, YDD=YLD)
CALL LOAD(ILUNFI, ZZZS, YDD=YLD)
CALL LOAD(ILUNFI, ZZSFTH, YDD=YLD)
CALL LOAD(ILUNFI, ZZSFRV, YDD=YLD)
CALL LOAD(ILUNFI, ZZSFSV, YDD=YLD)
CALL LOAD(ILUNFI, ZZSFU, YDD=YLD)
CALL LOAD(ILUNFI, ZZSFV, YDD=YLD)
CALL LOAD(ILUNFI, ZZPABST, YDD=YLD)
CALL LOAD(ILUNFI, ZZUT, YDD=YLD)
CALL LOAD(ILUNFI, ZZVT, YDD=YLD)
CALL LOAD(ILUNFI, ZZWT, YDD=YLD)
CALL LOAD(ILUNFI, ZZTKET, YDD=YLD)
CALL LOAD(ILUNFI, ZZSVT, YDD=YLD)
CALL LOAD(ILUNFI, ZZSRCT, YDD=YLD)
CALL LOAD(ILUNFI, ZZLENGTHM, YDD=YLD)
CALL LOAD(ILUNFI, ZZLENGTHH, YDD=YLD)
CALL LOAD(ILUNFI, ZZFMOIST, YDD=YLD)
CALL LOAD(ILUNFI, ZZBL_DEPTH, YDD=YLD)
CALL LOAD(ILUNFI, ZZSBL_DEPTH, YDD=YLD)
CALL LOAD(ILUNFI, ZZCEI, YDD=YLD)
CALL LOAD(ILUNFI, ZZTHLT, YDD=YLD)
CALL LOAD(ILUNFI, ZZRT, YDD=YLD)
CALL LOAD(ILUNFI, ZZRUS, YDD=YLD)
CALL LOAD(ILUNFI, ZZRVS, YDD=YLD)
CALL LOAD(ILUNFI, ZZRWS, YDD=YLD)
CALL LOAD(ILUNFI, ZZRTHLS, YDD=YLD)
CALL LOAD(ILUNFI, ZZRRS, YDD=YLD)
CALL LOAD(ILUNFI, ZZRSVS, YDD=YLD)
CALL LOAD(ILUNFI, ZZRTKES, YDD=YLD)
CALL LOAD(ILUNFI, ZZSIGS, YDD=YLD)
CALL LOAD(ILUNFI, ZZFLXZTHVMF, YDD=YLD)
CALL LOAD(ILUNFI, ZZFLXZUMF, YDD=YLD)
CALL LOAD(ILUNFI, ZZFLXZVMF, YDD=YLD)
CALL LOAD(ILUNFI, ZZWTH, YDD=YLD)
CALL LOAD(ILUNFI, ZZWRC, YDD=YLD)
CALL LOAD(ILUNFI, ZZWSV, YDD=YLD)
CALL LOAD(ILUNFI, ZZDP, YDD=YLD)
CALL LOAD(ILUNFI, ZZTP, YDD=YLD)
CALL LOAD(ILUNFI, ZZTDIFF, YDD=YLD)
CALL LOAD(ILUNFI, ZZTDISS, YDD=YLD)
!CALL LOAD(ILUNFI, ZZBUDGETS, YDD=YLD)
CALL LOAD(ILUNFI, ZZEDR, YDD=YLD)
!CALL LOAD(ILUNFI, ZZLEM, YDD=YLD)
!CALL LOAD(ILUNFI, ZZRTKEMS, YDD=YLD)
CALL LOAD(ILUNFI, ZZDPMF, YDD=YLD)
CALL LOAD(ILUNFI, ZZTPMF, YDD=YLD)
CALL LOAD(ILUNFI, ZZDRUS_TURB, YDD=YLD)
CALL LOAD(ILUNFI, ZZDRVS_TURB, YDD=YLD)
CALL LOAD(ILUNFI, ZZDRTHLS_TURB, YDD=YLD)
CALL LOAD(ILUNFI, ZZDRRTS_TURB, YDD=YLD)
CALL LOAD(ILUNFI, ZZDRSVS_TURB, YDD=YLD)
!CALL LOAD(ILUNFI, ZZTR, YDD=YLD)
!CALL LOAD(ILUNFI, ZZDISS, YDD=YLD)
!CALL LOAD(ILUNFI, ZZIBM_LS, YDD=YLD)
!CALL LOAD(ILUNFI, ZZIBM_XMUT, YDD=YLD)
!CALL LOAD(ILUNFI, ZZCURRENT_TKE_DISS, YDD=YLD)
!CALL LOAD(ILUNFI, ZZSSTFL, YDD=YLD)
!CALL LOAD(ILUNFI, ZZSSTFL_C, YDD=YLD)
!CALL LOAD(ILUNFI, ZZSSRFL_C, YDD=YLD)
!CALL LOAD(ILUNFI, ZZSSUFL_C, YDD=YLD)
!CALL LOAD(ILUNFI, ZZSSVFL_C, YDD=YLD)
!CALL LOAD(ILUNFI, ZZSSUFL, YDD=YLD)
!CALL LOAD(ILUNFI, ZZSSVFL, YDD=YLD)

CLOSE (ILUNFI)
CLOSE (ILUNCI)
OPEN (ILUNFI, NAME=TRIM (CLCASE_IN)//'/TURB.IN.dat',FORM='UNFORMATTED')
END SUBROUTINE

SUBROUTINE DIFFALL
IF (LLVERBOSE) PRINT *, " DIFF..."

ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/TURB.OUT.dat', FORM='UNFORMATTED')

CALL DIFF('ZZBL_DEPTH', ZZBL_DEPTH, KLUN=ILUNFO, YDD=YLD)
CALL DIFF('ZZSBL_DEPTH', ZZSBL_DEPTH, KLUN=ILUNFO, YDD=YLD)
CALL DIFF('ZZTHLT', ZZTHLT, KLUN=ILUNFO, YDD=YLD)
CALL DIFF('ZZRT', ZZRT, KLUN=ILUNFO, YDD=YLD)
CALL DIFF('ZZRUS', ZZRUS, KLUN=ILUNFO, YDD=YLD)
CALL DIFF('ZZRVS', ZZRVS, KLUN=ILUNFO, YDD=YLD)
CALL DIFF('ZZRWS', ZZRWS, KLUN=ILUNFO, YDD=YLD)
CALL DIFF('ZZRTHLS', ZZRTHLS, KLUN=ILUNFO, YDD=YLD)
CALL DIFF('ZZRRS', ZZRRS, KLUN=ILUNFO, YDD=YLD)
CALL DIFF('ZZRSVS', ZZRSVS, KLUN=ILUNFO, YDD=YLD)
CALL DIFF('ZZRTKES', ZZRTKES, KLUN=ILUNFO, YDD=YLD)
CALL DIFF('ZZSIGS', ZZSIGS, KLUN=ILUNFO, YDD=YLD)
CALL DIFF('ZZWTH', ZZWTH, KLUN=ILUNFO, YDD=YLD)
CALL DIFF('ZZWRC', ZZWRC, KLUN=ILUNFO, YDD=YLD)
CALL DIFF('ZZWSV', ZZWSV, KLUN=ILUNFO, YDD=YLD)
CALL DIFF('ZZDP', ZZDP, KLUN=ILUNFO, YDD=YLD)
CALL DIFF('ZZTP', ZZTP, KLUN=ILUNFO, YDD=YLD)
CALL DIFF('ZZTDIFF', ZZTDIFF, KLUN=ILUNFO, YDD=YLD)
CALL DIFF('ZZTDISS', ZZTDISS, KLUN=ILUNFO, YDD=YLD)
!CALL DIFF('ZZBUDGETS', ZZBUDGETS, KLUN=ILUNFO, YDD=YLD)
CALL DIFF('ZZEDR', ZZEDR, KLUN=ILUNFO, YDD=YLD)
!CALL DIFF('ZZLEM', ZZLEM, KLUN=ILUNFO, YDD=YLD)
CALL DIFF('ZZDPMF', ZZDPMF, KLUN=ILUNFO, YDD=YLD)
CALL DIFF('ZZTPMF', ZZTPMF, KLUN=ILUNFO, YDD=YLD)
CALL DIFF('ZZDRUS_TURB', ZZDRUS_TURB, KLUN=ILUNFO, YDD=YLD)
CALL DIFF('ZZDRVS_TURB', ZZDRVS_TURB, KLUN=ILUNFO, YDD=YLD)
CALL DIFF('ZZDRTHLS_TURB', ZZDRTHLS_TURB, KLUN=ILUNFO, YDD=YLD)
CALL DIFF('ZZDRRTS_TURB', ZZDRRTS_TURB, KLUN=ILUNFO, YDD=YLD)
CALL DIFF('ZZDRSVS_TURB', ZZDRSVS_TURB, KLUN=ILUNFO, YDD=YLD)
!CALL DIFF('ZZTR', ZZTR, KLUN=ILUNFO, YDD=YLD)
!CALL DIFF('ZZDISS', ZZDISS, KLUN=ILUNFO, YDD=YLD)
!CALL DIFF('ZZIBM_XMUT', ZZIBM_XMUT, KLUN=ILUNFO, YDD=YLD)
!CALL DIFF('ZZCURRENT_TKE_DISS', ZZCURRENT_TKE_DISS, KLUN=ILUNFO, YDD=YLD)

CLOSE(ILUNFO)

IF (LLVERBOSE) PRINT *, " ...DIFF"

END SUBROUTINE


SUBROUTINE SAVEIALL

ILUNCI = 77
ILUNFI = 78

OPEN (ILUNCI, NAME=TRIM (CLCASE_OUT)//'/TURB.CONST.dat', FORM='UNFORMATTED')
OPEN (ILUNFI, NAME=TRIM (CLCASE_OUT)//'/TURB.IN.dat',    FORM='UNFORMATTED')


CALL ACDC_SAVE(D, ILUNCI)
CALL ACDC_SAVE(CST, ILUNCI)
CALL ACDC_SAVE(CSTURB, ILUNCI)
!CALLACDC_ SAVE(BUCONF, ILUNCI)
CALL ACDC_SAVE(TURBN, ILUNCI)
CALL ACDC_SAVE(NEBN, ILUNCI)
CALL ACDC_SAVE(TLES, ILUNCI)
CALL SAVE(KGRADIENTSLEO, ILUNCI)
CALL SAVE(KGRADIENTSGOG, ILUNCI)
CALL SAVE(KRR, ILUNCI)
CALL SAVE(KRRL, ILUNCI)
CALL SAVE(KRRI, ILUNCI)
CALL SAVE(KSV, ILUNCI)
CALL SAVE(KSV_LGBEG, ILUNCI) 
CALL SAVE(KSV_LGEND, ILUNCI)
CALL SAVE(KSV_LIMA_NR, ILUNCI)
CALL SAVE(KSV_LIMA_NS, ILUNCI)
CALL SAVE(KSV_LIMA_NG, ILUNCI)
CALL SAVE(KSV_LIMA_NH, ILUNCI)
!CALL SAVE(HLBCX, ILUNCI)
!CALL SAVE(HLBCY, ILUNCI)
CALL SAVE(KSPLIT, ILUNCI) 
CALL SAVE(OCLOUDMODIFLM, ILUNCI)
CALL SAVE(KHALO, ILUNCI)
CALL SAVE(OCOMPUTE_SRC, ILUNCI)
CALL SAVE(OOCEAN, ILUNCI)
CALL SAVE(ODEEPOC, ILUNCI)
CALL SAVE(OFLYER, ILUNCI)
CALL SAVE(OFLAT, ILUNCI)
CALL SAVE(OCOUPLES, ILUNCI)
CALL SAVE(OBLOWSNOW, ILUNCI)
CALL SAVE(ODIAG_IN_RUN, ILUNCI)
CALL SAVE(OIBM, ILUNCI)
!CALL SAVE(HTURBLEN_CL, ILUNCI)
!CALL SAVE(HCLOUD, ILUNCI)
!CALL SAVE(HELEC, ILUNCI)
CALL SAVE(PRSNOW, ILUNCI)
CALL SAVE(PTSTEP, ILUNCI)
CALL SAVE(PCEI_MIN, ILUNCI) 
CALL SAVE(PCEI_MAX, ILUNCI)
CALL SAVE(PCOEF_AMPL_SAT, ILUNCI)
!TYPE(TBUDGETDATA_PTR), DIMENSION(KBUDGETS), INTENT(INOUT) :: TBUDGETS
CALL SAVE(KBUDGETS, ILUNCI)
CALL SAVE(ONOMIXLG, ILUNCI)
CALL SAVE(O2D, ILUNCI)

!CALL SAVE(ZZLBCX, ILUNFI, KLBOUND=LBOUND(ZZLBCX))
!CALL SAVE(ZZLBCY, ILUNFI, KLBOUND=LBOUND(ZZLBCY))
CALL SAVE(ZZDXX, ILUNFI, KLBOUND=LBOUND(ZZDXX))
CALL SAVE(ZZDYY, ILUNFI, KLBOUND=LBOUND(ZZDYY))
CALL SAVE(ZZDZZ, ILUNFI, KLBOUND=LBOUND(ZZDZZ))
CALL SAVE(ZZDZX, ILUNFI, KLBOUND=LBOUND(ZZDZX))
CALL SAVE(ZZDZY, ILUNFI, KLBOUND=LBOUND(ZZDZY))
CALL SAVE(ZZZZ, ILUNFI, KLBOUND=LBOUND(ZZZZ))
CALL SAVE(ZZDIRCOSXW, ILUNFI, KLBOUND=LBOUND(ZZDIRCOSXW))
CALL SAVE(ZZDIRCOSYW, ILUNFI, KLBOUND=LBOUND(ZZDIRCOSYW))
CALL SAVE(ZZDIRCOSZW, ILUNFI, KLBOUND=LBOUND(ZZDIRCOSZW))
CALL SAVE(ZZCOSSLOPE, ILUNFI, KLBOUND=LBOUND(ZZCOSSLOPE))
CALL SAVE(ZZSINSLOPE, ILUNFI, KLBOUND=LBOUND(ZZSINSLOPE))
CALL SAVE(ZZRHODJ, ILUNFI, KLBOUND=LBOUND(ZZRHODJ))
CALL SAVE(ZZTHVREF, ILUNFI, KLBOUND=LBOUND(ZZTHVREF))
CALL SAVE(ZZHGRADLEO, ILUNFI, KLBOUND=LBOUND(ZZHGRADLEO))
CALL SAVE(ZZHGRADGOG, ILUNFI, KLBOUND=LBOUND(ZZHGRADGOG))
CALL SAVE(ZZZS, ILUNFI, KLBOUND=LBOUND(ZZZS))
CALL SAVE(ZZSFTH, ILUNFI, KLBOUND=LBOUND(ZZSFTH))
CALL SAVE(ZZSFRV, ILUNFI, KLBOUND=LBOUND(ZZSFRV))
CALL SAVE(ZZSFSV, ILUNFI, KLBOUND=LBOUND(ZZSFSV))
CALL SAVE(ZZSFU, ILUNFI, KLBOUND=LBOUND(ZZSFU))
CALL SAVE(ZZSFV, ILUNFI, KLBOUND=LBOUND(ZZSFV))
CALL SAVE(ZZPABST, ILUNFI, KLBOUND=LBOUND(ZZPABST))
CALL SAVE(ZZUT, ILUNFI, KLBOUND=LBOUND(ZZUT))
CALL SAVE(ZZVT, ILUNFI, KLBOUND=LBOUND(ZZVT))
CALL SAVE(ZZWT, ILUNFI, KLBOUND=LBOUND(ZZWT))
CALL SAVE(ZZTKET, ILUNFI, KLBOUND=LBOUND(ZZTKET))
CALL SAVE(ZZSVT, ILUNFI, KLBOUND=LBOUND(ZZSVT))
CALL SAVE(ZZSRCT, ILUNFI, KLBOUND=LBOUND(ZZSRCT))
CALL SAVE(ZZLENGTHM, ILUNFI, KLBOUND=LBOUND(ZZLENGTHM))
CALL SAVE(ZZLENGTHH, ILUNFI, KLBOUND=LBOUND(ZZLENGTHH))
CALL SAVE(ZZFMOIST, ILUNFI, KLBOUND=LBOUND(ZZFMOIST))
CALL SAVE(ZZBL_DEPTH, ILUNFI, KLBOUND=LBOUND(ZZBL_DEPTH))
CALL SAVE(ZZSBL_DEPTH, ILUNFI, KLBOUND=LBOUND(ZZSBL_DEPTH))
CALL SAVE(ZZCEI, ILUNFI, KLBOUND=LBOUND(ZZCEI))
CALL SAVE(ZZTHLT, ILUNFI, KLBOUND=LBOUND(ZZTHLT))
CALL SAVE(ZZRT, ILUNFI, KLBOUND=LBOUND(ZZRT))
CALL SAVE(ZZRUS, ILUNFI, KLBOUND=LBOUND(ZZRUS))
CALL SAVE(ZZRVS, ILUNFI, KLBOUND=LBOUND(ZZRVS))
CALL SAVE(ZZRWS, ILUNFI, KLBOUND=LBOUND(ZZRWS))
CALL SAVE(ZZRTHLS, ILUNFI, KLBOUND=LBOUND(ZZRTHLS))
CALL SAVE(ZZRRS, ILUNFI, KLBOUND=LBOUND(ZZRRS))
CALL SAVE(ZZRSVS, ILUNFI, KLBOUND=LBOUND(ZZRSVS))
CALL SAVE(ZZRTKES, ILUNFI, KLBOUND=LBOUND(ZZRTKES))
CALL SAVE(ZZSIGS, ILUNFI, KLBOUND=LBOUND(ZZSIGS))
CALL SAVE(ZZFLXZTHVMF, ILUNFI, KLBOUND=LBOUND(ZZFLXZTHVMF))
CALL SAVE(ZZFLXZUMF, ILUNFI, KLBOUND=LBOUND(ZZFLXZUMF))
CALL SAVE(ZZFLXZVMF, ILUNFI, KLBOUND=LBOUND(ZZFLXZVMF))
CALL SAVE(ZZWTH, ILUNFI, KLBOUND=LBOUND(ZZWTH))
CALL SAVE(ZZWRC, ILUNFI, KLBOUND=LBOUND(ZZWRC))
CALL SAVE(ZZWSV, ILUNFI, KLBOUND=LBOUND(ZZWSV))
CALL SAVE(ZZDP, ILUNFI, KLBOUND=LBOUND(ZZDP))
CALL SAVE(ZZTP, ILUNFI, KLBOUND=LBOUND(ZZTP))
CALL SAVE(ZZTDIFF, ILUNFI, KLBOUND=LBOUND(ZZTDIFF))
CALL SAVE(ZZTDISS, ILUNFI, KLBOUND=LBOUND(ZZTDISS))
!CALL SAVE(ZZBUDGETS, ILUNFI, KLBOUND=LBOUND(ZZBUDGETS))
CALL SAVE(ZZEDR, ILUNFI, KLBOUND=LBOUND(ZZEDR))
!CALL SAVE(ZZLEM, ILUNFI, KLBOUND=LBOUND(ZZLEM))
!CALL SAVE(ZZRTKEMS, ILUNFI, KLBOUND=LBOUND(ZZRTKEMS))
CALL SAVE(ZZDPMF, ILUNFI, KLBOUND=LBOUND(ZZDPMF))
CALL SAVE(ZZTPMF, ILUNFI, KLBOUND=LBOUND(ZZTPMF))
CALL SAVE(ZZDRUS_TURB, ILUNFI, KLBOUND=LBOUND(ZZDRUS_TURB))
CALL SAVE(ZZDRVS_TURB, ILUNFI, KLBOUND=LBOUND(ZZDRVS_TURB))
CALL SAVE(ZZDRTHLS_TURB, ILUNFI, KLBOUND=LBOUND(ZZDRTHLS_TURB))
CALL SAVE(ZZDRRTS_TURB, ILUNFI, KLBOUND=LBOUND(ZZDRRTS_TURB))
CALL SAVE(ZZDRSVS_TURB, ILUNFI, KLBOUND=LBOUND(ZZDRSVS_TURB))
!CALL SAVE(ZZTR, ILUNFI, KLBOUND=LBOUND(ZZTR))
!CALL SAVE(ZZDISS, ILUNFI, KLBOUND=LBOUND(ZZDISS))
!CALL SAVE(ZZIBM_LS, ILUNFI, KLBOUND=LBOUND(ZZIBM_LS))
!CALL SAVE(ZZIBM_XMUT, ILUNFI, KLBOUND=LBOUND(ZZIBM_XMUT))
!CALL SAVE(ZZCURRENT_TKE_DISS, ILUNFI, KLBOUND=LBOUND(ZZCURRENT_TKE_DISS))
!CALL SAVE(ZZSSTFL, ILUNFI, KLBOUND=LBOUND(ZZSSTFL))
!CALL SAVE(ZZSSTFL_C, ILUNFI, KLBOUND=LBOUND(ZZSSTFL_C))
!CALL SAVE(ZZSSRFL_C, ILUNFI, KLBOUND=LBOUND(ZZSSRFL_C))
!CALL SAVE(ZZSSUFL_C, ILUNFI, KLBOUND=LBOUND(ZZSSUFL_C))
!CALL SAVE(ZZSSVFL_C, ILUNFI, KLBOUND=LBOUND(ZZSSVFL_C))
!CALL SAVE(ZZSSUFL, ILUNFI, KLBOUND=LBOUND(ZZSSUFL))
!CALL SAVE(ZZSSVFL, ILUNFI, KLBOUND=LBOUND(ZZSSVFL))

CLOSE (ILUNFI)
CLOSE (ILUNCI)

END SUBROUTINE

SUBROUTINE SAVEOALL

ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_OUT)//'/TURB.OUT.dat', FORM='UNFORMATTED')

CALL SAVE(ZZBL_DEPTH, ILUNFO, KLBOUND=LBOUND(ZZBL_DEPTH))
CALL SAVE(ZZSBL_DEPTH, ILUNFO, KLBOUND=LBOUND(ZZSBL_DEPTH))
CALL SAVE(ZZTHLT, ILUNFO, KLBOUND=LBOUND(ZZTHLT))
CALL SAVE(ZZRT, ILUNFO, KLBOUND=LBOUND(ZZRT))
CALL SAVE(ZZRUS, ILUNFO, KLBOUND=LBOUND(ZZRUS))
CALL SAVE(ZZRVS, ILUNFO, KLBOUND=LBOUND(ZZRVS))
CALL SAVE(ZZRWS, ILUNFO, KLBOUND=LBOUND(ZZRWS))
CALL SAVE(ZZRTHLS, ILUNFO, KLBOUND=LBOUND(ZZRTHLS))
CALL SAVE(ZZRRS, ILUNFO, KLBOUND=LBOUND(ZZRRS))
CALL SAVE(ZZRSVS, ILUNFO, KLBOUND=LBOUND(ZZRSVS))
CALL SAVE(ZZRTKES, ILUNFO, KLBOUND=LBOUND(ZZRTKES))
CALL SAVE(ZZSIGS, ILUNFO, KLBOUND=LBOUND(ZZSIGS))
CALL SAVE(ZZWTH, ILUNFO, KLBOUND=LBOUND(ZZWTH))
CALL SAVE(ZZWRC, ILUNFO, KLBOUND=LBOUND(ZZWRC))
CALL SAVE(ZZWSV, ILUNFO, KLBOUND=LBOUND(ZZWSV))
CALL SAVE(ZZDP, ILUNFO, KLBOUND=LBOUND(ZZDP))
CALL SAVE(ZZTP, ILUNFO, KLBOUND=LBOUND(ZZTP))
CALL SAVE(ZZTDIFF, ILUNFO, KLBOUND=LBOUND(ZZTDIFF))
CALL SAVE(ZZTDISS, ILUNFO, KLBOUND=LBOUND(ZZTDISS))
!CALL SAVE(ZZBUDGETS, ILUNFO, KLBOUND=LBOUND(ZZBUDGETS))
CALL SAVE(ZZEDR, ILUNFO, KLBOUND=LBOUND(ZZEDR))
!CALL SAVE(ZZLEM, ILUNFO, KLBOUND=LBOUND(ZZLEM))
CALL SAVE(ZZDPMF, ILUNFO, KLBOUND=LBOUND(ZZDPMF))
CALL SAVE(ZZTPMF, ILUNFO, KLBOUND=LBOUND(ZZTPMF))
CALL SAVE(ZZDRUS_TURB, ILUNFO, KLBOUND=LBOUND(ZZDRUS_TURB))
CALL SAVE(ZZDRVS_TURB, ILUNFO, KLBOUND=LBOUND(ZZDRVS_TURB))
CALL SAVE(ZZDRTHLS_TURB, ILUNFO, KLBOUND=LBOUND(ZZDRTHLS_TURB))
CALL SAVE(ZZDRRTS_TURB, ILUNFO, KLBOUND=LBOUND(ZZDRRTS_TURB))
CALL SAVE(ZZDRSVS_TURB, ILUNFO, KLBOUND=LBOUND(ZZDRSVS_TURB))
!CALL SAVE(ZZTR, ILUNFO, KLBOUND=LBOUND(ZZTR))
!CALL SAVE(ZZDISS, ILUNFO, KLBOUND=LBOUND(ZZDISS))
!CALL SAVE(ZZIBM_XMUT, ILUNFO, KLBOUND=LBOUND(ZZIBM_XMUT))
!CALL SAVE(ZZCURRENT_TKE_DISS, ILUNFO, KLBOUND=LBOUND(ZZCURRENT_TKE_DISS))

CLOSE (ILUNFO)

END SUBROUTINE

END PROGRAM MAIN_TURB
