MODULE UTIL_NEB_T_MOD

USE MODD_NEB_N, ONLY : NEB_T

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_NEB_T
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_NEB_T
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_NEB_T
END INTERFACE




INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_NEB_T
END INTERFACE


CONTAINS

SUBROUTINE ACDC_SAVE_NEB_T (SELF, KLUN)

IMPLICIT NONE
TYPE (NEB_T), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%XTMINMIX
WRITE (KLUN) SELF%XTMAXMIX
WRITE (KLUN) SELF%LHGT_QS
WRITE (KLUN) SELF%CFRAC_ICE_ADJUST
WRITE (KLUN) SELF%CFRAC_ICE_SHALLOW_MF
WRITE (KLUN) SELF%VSIGQSAT
WRITE (KLUN) SELF%CCONDENS
WRITE (KLUN) SELF%CLAMBDA3
WRITE (KLUN) SELF%LSTATNW
WRITE (KLUN) SELF%LSIGMAS
WRITE (KLUN) SELF%LSUBG_COND
WRITE (KLUN) SELF%LCONDBORN
END SUBROUTINE

SUBROUTINE ACDC_LOAD_NEB_T (SELF, KLUN)

IMPLICIT NONE
TYPE (NEB_T), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%XTMINMIX
READ (KLUN) SELF%XTMAXMIX
READ (KLUN) SELF%LHGT_QS
READ (KLUN) SELF%CFRAC_ICE_ADJUST
READ (KLUN) SELF%CFRAC_ICE_SHALLOW_MF
READ (KLUN) SELF%VSIGQSAT
READ (KLUN) SELF%CCONDENS
READ (KLUN) SELF%CLAMBDA3
READ (KLUN) SELF%LSTATNW
READ (KLUN) SELF%LSIGMAS
READ (KLUN) SELF%LSUBG_COND
READ (KLUN) SELF%LCONDBORN
END SUBROUTINE

SUBROUTINE ACDC_COPY_NEB_T (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (NEB_T), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE







SUBROUTINE ACDC_WIPE_NEB_T (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (NEB_T), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
