MODULE UTIL_TURB_T_MOD

USE MODD_TURB_N, ONLY : TURB_T

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_TURB_T
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_TURB_T
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_TURB_T
END INTERFACE




INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_TURB_T
END INTERFACE


CONTAINS

SUBROUTINE ACDC_SAVE_TURB_T (SELF, KLUN)

IMPLICIT NONE
TYPE (TURB_T), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LXCEI, LXDISS, LXDYP, LXLEM, LXSSRFL_C, LXSSTFL_C, LXSSUFL_C, LXSSVFL_C, LXTHP, LXTR
WRITE (KLUN) SELF%XIMPL
WRITE (KLUN) SELF%XTKEMIN
WRITE (KLUN) SELF%XCED
WRITE (KLUN) SELF%XCTP
WRITE (KLUN) SELF%XCSHF
WRITE (KLUN) SELF%XCHF
WRITE (KLUN) SELF%XCTV
WRITE (KLUN) SELF%XCHV
WRITE (KLUN) SELF%XCHT1
WRITE (KLUN) SELF%XCHT2
WRITE (KLUN) SELF%XCPR1
WRITE (KLUN) SELF%XCADAP
WRITE (KLUN) SELF%CTURBLEN
WRITE (KLUN) SELF%CTURBDIM
WRITE (KLUN) SELF%LTURB_FLX
WRITE (KLUN) SELF%LTURB_DIAG
WRITE (KLUN) SELF%LSIG_CONV
WRITE (KLUN) SELF%LHARAT
WRITE (KLUN) SELF%LBL89TOP
WRITE (KLUN) SELF%LBL89EXP
WRITE (KLUN) SELF%LRMC01
WRITE (KLUN) SELF%CTOM
LXDYP = ASSOCIATED (SELF%XDYP)
WRITE (KLUN) LXDYP
IF (LXDYP) THEN
  WRITE (KLUN) LBOUND (SELF%XDYP)
  WRITE (KLUN) UBOUND (SELF%XDYP)
  WRITE (KLUN) SELF%XDYP
ENDIF
LXTHP = ASSOCIATED (SELF%XTHP)
WRITE (KLUN) LXTHP
IF (LXTHP) THEN
  WRITE (KLUN) LBOUND (SELF%XTHP)
  WRITE (KLUN) UBOUND (SELF%XTHP)
  WRITE (KLUN) SELF%XTHP
ENDIF
LXTR = ASSOCIATED (SELF%XTR)
WRITE (KLUN) LXTR
IF (LXTR) THEN
  WRITE (KLUN) LBOUND (SELF%XTR)
  WRITE (KLUN) UBOUND (SELF%XTR)
  WRITE (KLUN) SELF%XTR
ENDIF
LXDISS = ASSOCIATED (SELF%XDISS)
WRITE (KLUN) LXDISS
IF (LXDISS) THEN
  WRITE (KLUN) LBOUND (SELF%XDISS)
  WRITE (KLUN) UBOUND (SELF%XDISS)
  WRITE (KLUN) SELF%XDISS
ENDIF
LXLEM = ASSOCIATED (SELF%XLEM)
WRITE (KLUN) LXLEM
IF (LXLEM) THEN
  WRITE (KLUN) LBOUND (SELF%XLEM)
  WRITE (KLUN) UBOUND (SELF%XLEM)
  WRITE (KLUN) SELF%XLEM
ENDIF
LXSSUFL_C = ASSOCIATED (SELF%XSSUFL_C)
WRITE (KLUN) LXSSUFL_C
IF (LXSSUFL_C) THEN
  WRITE (KLUN) LBOUND (SELF%XSSUFL_C)
  WRITE (KLUN) UBOUND (SELF%XSSUFL_C)
  WRITE (KLUN) SELF%XSSUFL_C
ENDIF
LXSSVFL_C = ASSOCIATED (SELF%XSSVFL_C)
WRITE (KLUN) LXSSVFL_C
IF (LXSSVFL_C) THEN
  WRITE (KLUN) LBOUND (SELF%XSSVFL_C)
  WRITE (KLUN) UBOUND (SELF%XSSVFL_C)
  WRITE (KLUN) SELF%XSSVFL_C
ENDIF
LXSSTFL_C = ASSOCIATED (SELF%XSSTFL_C)
WRITE (KLUN) LXSSTFL_C
IF (LXSSTFL_C) THEN
  WRITE (KLUN) LBOUND (SELF%XSSTFL_C)
  WRITE (KLUN) UBOUND (SELF%XSSTFL_C)
  WRITE (KLUN) SELF%XSSTFL_C
ENDIF
LXSSRFL_C = ASSOCIATED (SELF%XSSRFL_C)
WRITE (KLUN) LXSSRFL_C
IF (LXSSRFL_C) THEN
  WRITE (KLUN) LBOUND (SELF%XSSRFL_C)
  WRITE (KLUN) UBOUND (SELF%XSSRFL_C)
  WRITE (KLUN) SELF%XSSRFL_C
ENDIF
WRITE (KLUN) SELF%LLEONARD
WRITE (KLUN) SELF%XCOEFHGRADTHL
WRITE (KLUN) SELF%XCOEFHGRADRM
WRITE (KLUN) SELF%XALTHGRAD
WRITE (KLUN) SELF%LGOGER
WRITE (KLUN) SELF%XSMAG
WRITE (KLUN) SELF%XCLDTHOLD
WRITE (KLUN) SELF%XLINI
WRITE (KLUN) SELF%LROTATE_WIND
WRITE (KLUN) SELF%LTKEMINTURB
WRITE (KLUN) SELF%LPROJQITURB
WRITE (KLUN) SELF%LSMOOTH_PRANDTL
WRITE (KLUN) SELF%XMINSIGS
WRITE (KLUN) SELF%XBL89EXP
WRITE (KLUN) SELF%XUSRBL89
WRITE (KLUN) SELF%NTURBSPLIT
WRITE (KLUN) SELF%LCLOUDMODIFLM
WRITE (KLUN) SELF%CTURBLEN_CLOUD
WRITE (KLUN) SELF%XCOEF_AMPL_SAT
WRITE (KLUN) SELF%XCEI_MIN
WRITE (KLUN) SELF%XCEI_MAX
LXCEI = ASSOCIATED (SELF%XCEI)
WRITE (KLUN) LXCEI
IF (LXCEI) THEN
  WRITE (KLUN) LBOUND (SELF%XCEI)
  WRITE (KLUN) UBOUND (SELF%XCEI)
  WRITE (KLUN) SELF%XCEI
ENDIF
WRITE (KLUN) SELF%LTURB_PRECIP
WRITE (KLUN) SELF%LDYNMF
WRITE (KLUN) SELF%LTHERMMF
END SUBROUTINE

SUBROUTINE ACDC_LOAD_TURB_T (SELF, KLUN)

IMPLICIT NONE
TYPE (TURB_T), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL3(3), IU3(3)
LOGICAL :: LXCEI, LXDISS, LXDYP, LXLEM, LXSSRFL_C, LXSSTFL_C, LXSSUFL_C, LXSSVFL_C, LXTHP, LXTR
READ (KLUN) SELF%XIMPL
READ (KLUN) SELF%XTKEMIN
READ (KLUN) SELF%XCED
READ (KLUN) SELF%XCTP
READ (KLUN) SELF%XCSHF
READ (KLUN) SELF%XCHF
READ (KLUN) SELF%XCTV
READ (KLUN) SELF%XCHV
READ (KLUN) SELF%XCHT1
READ (KLUN) SELF%XCHT2
READ (KLUN) SELF%XCPR1
READ (KLUN) SELF%XCADAP
READ (KLUN) SELF%CTURBLEN
READ (KLUN) SELF%CTURBDIM
READ (KLUN) SELF%LTURB_FLX
READ (KLUN) SELF%LTURB_DIAG
READ (KLUN) SELF%LSIG_CONV
READ (KLUN) SELF%LHARAT
READ (KLUN) SELF%LBL89TOP
READ (KLUN) SELF%LBL89EXP
READ (KLUN) SELF%LRMC01
READ (KLUN) SELF%CTOM
READ (KLUN) LXDYP
IF (LXDYP) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%XDYP (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) SELF%XDYP
ELSE
  NULLIFY (SELF%XDYP)
ENDIF
READ (KLUN) LXTHP
IF (LXTHP) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%XTHP (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) SELF%XTHP
ELSE
  NULLIFY (SELF%XTHP)
ENDIF
READ (KLUN) LXTR
IF (LXTR) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%XTR (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) SELF%XTR
ELSE
  NULLIFY (SELF%XTR)
ENDIF
READ (KLUN) LXDISS
IF (LXDISS) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%XDISS (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) SELF%XDISS
ELSE
  NULLIFY (SELF%XDISS)
ENDIF
READ (KLUN) LXLEM
IF (LXLEM) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%XLEM (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) SELF%XLEM
ELSE
  NULLIFY (SELF%XLEM)
ENDIF
READ (KLUN) LXSSUFL_C
IF (LXSSUFL_C) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%XSSUFL_C (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) SELF%XSSUFL_C
ELSE
  NULLIFY (SELF%XSSUFL_C)
ENDIF
READ (KLUN) LXSSVFL_C
IF (LXSSVFL_C) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%XSSVFL_C (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) SELF%XSSVFL_C
ELSE
  NULLIFY (SELF%XSSVFL_C)
ENDIF
READ (KLUN) LXSSTFL_C
IF (LXSSTFL_C) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%XSSTFL_C (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) SELF%XSSTFL_C
ELSE
  NULLIFY (SELF%XSSTFL_C)
ENDIF
READ (KLUN) LXSSRFL_C
IF (LXSSRFL_C) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%XSSRFL_C (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) SELF%XSSRFL_C
ELSE
  NULLIFY (SELF%XSSRFL_C)
ENDIF
READ (KLUN) SELF%LLEONARD
READ (KLUN) SELF%XCOEFHGRADTHL
READ (KLUN) SELF%XCOEFHGRADRM
READ (KLUN) SELF%XALTHGRAD
READ (KLUN) SELF%LGOGER
READ (KLUN) SELF%XSMAG
READ (KLUN) SELF%XCLDTHOLD
READ (KLUN) SELF%XLINI
READ (KLUN) SELF%LROTATE_WIND
READ (KLUN) SELF%LTKEMINTURB
READ (KLUN) SELF%LPROJQITURB
READ (KLUN) SELF%LSMOOTH_PRANDTL
READ (KLUN) SELF%XMINSIGS
READ (KLUN) SELF%XBL89EXP
READ (KLUN) SELF%XUSRBL89
READ (KLUN) SELF%NTURBSPLIT
READ (KLUN) SELF%LCLOUDMODIFLM
READ (KLUN) SELF%CTURBLEN_CLOUD
READ (KLUN) SELF%XCOEF_AMPL_SAT
READ (KLUN) SELF%XCEI_MIN
READ (KLUN) SELF%XCEI_MAX
READ (KLUN) LXCEI
IF (LXCEI) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%XCEI (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) SELF%XCEI
ELSE
  NULLIFY (SELF%XCEI)
ENDIF
READ (KLUN) SELF%LTURB_PRECIP
READ (KLUN) SELF%LDYNMF
READ (KLUN) SELF%LTHERMMF
END SUBROUTINE

SUBROUTINE ACDC_COPY_TURB_T (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TURB_T), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LXCEI, LXDISS, LXDYP, LXLEM, LXSSRFL_C, LXSSTFL_C, LXSSUFL_C, LXSSVFL_C, LXTHP, LXTR
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

LXDYP = ASSOCIATED (SELF%XDYP)
IF (LXDYP) THEN
  !$ACC ENTER DATA CREATE (SELF%XDYP)
  !$ACC UPDATE DEVICE (SELF%XDYP)
  !$ACC ENTER DATA ATTACH (SELF%XDYP)
ENDIF

LXTHP = ASSOCIATED (SELF%XTHP)
IF (LXTHP) THEN
  !$ACC ENTER DATA CREATE (SELF%XTHP)
  !$ACC UPDATE DEVICE (SELF%XTHP)
  !$ACC ENTER DATA ATTACH (SELF%XTHP)
ENDIF

LXTR = ASSOCIATED (SELF%XTR)
IF (LXTR) THEN
  !$ACC ENTER DATA CREATE (SELF%XTR)
  !$ACC UPDATE DEVICE (SELF%XTR)
  !$ACC ENTER DATA ATTACH (SELF%XTR)
ENDIF

LXDISS = ASSOCIATED (SELF%XDISS)
IF (LXDISS) THEN
  !$ACC ENTER DATA CREATE (SELF%XDISS)
  !$ACC UPDATE DEVICE (SELF%XDISS)
  !$ACC ENTER DATA ATTACH (SELF%XDISS)
ENDIF

LXLEM = ASSOCIATED (SELF%XLEM)
IF (LXLEM) THEN
  !$ACC ENTER DATA CREATE (SELF%XLEM)
  !$ACC UPDATE DEVICE (SELF%XLEM)
  !$ACC ENTER DATA ATTACH (SELF%XLEM)
ENDIF

LXSSUFL_C = ASSOCIATED (SELF%XSSUFL_C)
IF (LXSSUFL_C) THEN
  !$ACC ENTER DATA CREATE (SELF%XSSUFL_C)
  !$ACC UPDATE DEVICE (SELF%XSSUFL_C)
  !$ACC ENTER DATA ATTACH (SELF%XSSUFL_C)
ENDIF

LXSSVFL_C = ASSOCIATED (SELF%XSSVFL_C)
IF (LXSSVFL_C) THEN
  !$ACC ENTER DATA CREATE (SELF%XSSVFL_C)
  !$ACC UPDATE DEVICE (SELF%XSSVFL_C)
  !$ACC ENTER DATA ATTACH (SELF%XSSVFL_C)
ENDIF

LXSSTFL_C = ASSOCIATED (SELF%XSSTFL_C)
IF (LXSSTFL_C) THEN
  !$ACC ENTER DATA CREATE (SELF%XSSTFL_C)
  !$ACC UPDATE DEVICE (SELF%XSSTFL_C)
  !$ACC ENTER DATA ATTACH (SELF%XSSTFL_C)
ENDIF

LXSSRFL_C = ASSOCIATED (SELF%XSSRFL_C)
IF (LXSSRFL_C) THEN
  !$ACC ENTER DATA CREATE (SELF%XSSRFL_C)
  !$ACC UPDATE DEVICE (SELF%XSSRFL_C)
  !$ACC ENTER DATA ATTACH (SELF%XSSRFL_C)
ENDIF

LXCEI = ASSOCIATED (SELF%XCEI)
IF (LXCEI) THEN
  !$ACC ENTER DATA CREATE (SELF%XCEI)
  !$ACC UPDATE DEVICE (SELF%XCEI)
  !$ACC ENTER DATA ATTACH (SELF%XCEI)
ENDIF

END SUBROUTINE







SUBROUTINE ACDC_WIPE_TURB_T (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TURB_T), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LXCEI, LXDISS, LXDYP, LXLEM, LXSSRFL_C, LXSSTFL_C, LXSSUFL_C, LXSSVFL_C, LXTHP, LXTR
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LXDYP = ASSOCIATED (SELF%XDYP)
IF (LXDYP) THEN
  !$ACC EXIT DATA DETACH (SELF%XDYP)
  !$ACC EXIT DATA DELETE (SELF%XDYP)
ENDIF

LXTHP = ASSOCIATED (SELF%XTHP)
IF (LXTHP) THEN
  !$ACC EXIT DATA DETACH (SELF%XTHP)
  !$ACC EXIT DATA DELETE (SELF%XTHP)
ENDIF

LXTR = ASSOCIATED (SELF%XTR)
IF (LXTR) THEN
  !$ACC EXIT DATA DETACH (SELF%XTR)
  !$ACC EXIT DATA DELETE (SELF%XTR)
ENDIF

LXDISS = ASSOCIATED (SELF%XDISS)
IF (LXDISS) THEN
  !$ACC EXIT DATA DETACH (SELF%XDISS)
  !$ACC EXIT DATA DELETE (SELF%XDISS)
ENDIF

LXLEM = ASSOCIATED (SELF%XLEM)
IF (LXLEM) THEN
  !$ACC EXIT DATA DETACH (SELF%XLEM)
  !$ACC EXIT DATA DELETE (SELF%XLEM)
ENDIF

LXSSUFL_C = ASSOCIATED (SELF%XSSUFL_C)
IF (LXSSUFL_C) THEN
  !$ACC EXIT DATA DETACH (SELF%XSSUFL_C)
  !$ACC EXIT DATA DELETE (SELF%XSSUFL_C)
ENDIF

LXSSVFL_C = ASSOCIATED (SELF%XSSVFL_C)
IF (LXSSVFL_C) THEN
  !$ACC EXIT DATA DETACH (SELF%XSSVFL_C)
  !$ACC EXIT DATA DELETE (SELF%XSSVFL_C)
ENDIF

LXSSTFL_C = ASSOCIATED (SELF%XSSTFL_C)
IF (LXSSTFL_C) THEN
  !$ACC EXIT DATA DETACH (SELF%XSSTFL_C)
  !$ACC EXIT DATA DELETE (SELF%XSSTFL_C)
ENDIF

LXSSRFL_C = ASSOCIATED (SELF%XSSRFL_C)
IF (LXSSRFL_C) THEN
  !$ACC EXIT DATA DETACH (SELF%XSSRFL_C)
  !$ACC EXIT DATA DELETE (SELF%XSSRFL_C)
ENDIF

LXCEI = ASSOCIATED (SELF%XCEI)
IF (LXCEI) THEN
  !$ACC EXIT DATA DETACH (SELF%XCEI)
  !$ACC EXIT DATA DELETE (SELF%XCEI)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
