MODULE UTIL_CST_T_MOD

USE MODD_CST, ONLY : CST_T

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_CST_T
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_CST_T
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_CST_T
END INTERFACE




INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_CST_T
END INTERFACE


CONTAINS

SUBROUTINE ACDC_SAVE_CST_T (SELF, KLUN)

IMPLICIT NONE
TYPE (CST_T), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%XPI
WRITE (KLUN) SELF%XKARMAN
WRITE (KLUN) SELF%XLIGHTSPEED
WRITE (KLUN) SELF%XPLANCK
WRITE (KLUN) SELF%XBOLTZ
WRITE (KLUN) SELF%XAVOGADRO
WRITE (KLUN) SELF%XDAY
WRITE (KLUN) SELF%XSIYEA
WRITE (KLUN) SELF%XSIDAY
WRITE (KLUN) SELF%NDAYSEC
WRITE (KLUN) SELF%XOMEGA
WRITE (KLUN) SELF%XRADIUS
WRITE (KLUN) SELF%XG
WRITE (KLUN) SELF%XP00
WRITE (KLUN) SELF%XP00OCEAN
WRITE (KLUN) SELF%XRH00OCEAN
WRITE (KLUN) SELF%XTH00
WRITE (KLUN) SELF%XTH00OCEAN
WRITE (KLUN) SELF%XSA00OCEAN
WRITE (KLUN) SELF%XSTEFAN
WRITE (KLUN) SELF%XI0
WRITE (KLUN) SELF%XMD
WRITE (KLUN) SELF%XMV
WRITE (KLUN) SELF%XRD
WRITE (KLUN) SELF%XRV
WRITE (KLUN) SELF%XEPSILO
WRITE (KLUN) SELF%XCPD
WRITE (KLUN) SELF%XCPV
WRITE (KLUN) SELF%XRHOLW
WRITE (KLUN) SELF%XCL
WRITE (KLUN) SELF%XCI
WRITE (KLUN) SELF%XTT
WRITE (KLUN) SELF%XLVTT
WRITE (KLUN) SELF%XLSTT
WRITE (KLUN) SELF%XLMTT
WRITE (KLUN) SELF%XESTT
WRITE (KLUN) SELF%XALPW
WRITE (KLUN) SELF%XBETAW
WRITE (KLUN) SELF%XGAMW
WRITE (KLUN) SELF%XALPI
WRITE (KLUN) SELF%XBETAI
WRITE (KLUN) SELF%XGAMI
WRITE (KLUN) SELF%XCONDI
WRITE (KLUN) SELF%XALPHAOC
WRITE (KLUN) SELF%XBETAOC
WRITE (KLUN) SELF%XROC
WRITE (KLUN) SELF%XD1
WRITE (KLUN) SELF%XD2
WRITE (KLUN) SELF%XRHOLI
WRITE (KLUN) SELF%RDSRV
WRITE (KLUN) SELF%RDSCPD
WRITE (KLUN) SELF%RINVXP00
WRITE (KLUN) SELF%XMNH_TINY
WRITE (KLUN) SELF%XMNH_TINY_12
WRITE (KLUN) SELF%XMNH_EPSILON
WRITE (KLUN) SELF%XMNH_HUGE
WRITE (KLUN) SELF%XMNH_HUGE_12_LOG
WRITE (KLUN) SELF%XEPS_DT
WRITE (KLUN) SELF%XRES_FLAT_CART
WRITE (KLUN) SELF%XRES_OTHER
WRITE (KLUN) SELF%XRES_PREP
END SUBROUTINE

SUBROUTINE ACDC_LOAD_CST_T (SELF, KLUN)

IMPLICIT NONE
TYPE (CST_T), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%XPI
READ (KLUN) SELF%XKARMAN
READ (KLUN) SELF%XLIGHTSPEED
READ (KLUN) SELF%XPLANCK
READ (KLUN) SELF%XBOLTZ
READ (KLUN) SELF%XAVOGADRO
READ (KLUN) SELF%XDAY
READ (KLUN) SELF%XSIYEA
READ (KLUN) SELF%XSIDAY
READ (KLUN) SELF%NDAYSEC
READ (KLUN) SELF%XOMEGA
READ (KLUN) SELF%XRADIUS
READ (KLUN) SELF%XG
READ (KLUN) SELF%XP00
READ (KLUN) SELF%XP00OCEAN
READ (KLUN) SELF%XRH00OCEAN
READ (KLUN) SELF%XTH00
READ (KLUN) SELF%XTH00OCEAN
READ (KLUN) SELF%XSA00OCEAN
READ (KLUN) SELF%XSTEFAN
READ (KLUN) SELF%XI0
READ (KLUN) SELF%XMD
READ (KLUN) SELF%XMV
READ (KLUN) SELF%XRD
READ (KLUN) SELF%XRV
READ (KLUN) SELF%XEPSILO
READ (KLUN) SELF%XCPD
READ (KLUN) SELF%XCPV
READ (KLUN) SELF%XRHOLW
READ (KLUN) SELF%XCL
READ (KLUN) SELF%XCI
READ (KLUN) SELF%XTT
READ (KLUN) SELF%XLVTT
READ (KLUN) SELF%XLSTT
READ (KLUN) SELF%XLMTT
READ (KLUN) SELF%XESTT
READ (KLUN) SELF%XALPW
READ (KLUN) SELF%XBETAW
READ (KLUN) SELF%XGAMW
READ (KLUN) SELF%XALPI
READ (KLUN) SELF%XBETAI
READ (KLUN) SELF%XGAMI
READ (KLUN) SELF%XCONDI
READ (KLUN) SELF%XALPHAOC
READ (KLUN) SELF%XBETAOC
READ (KLUN) SELF%XROC
READ (KLUN) SELF%XD1
READ (KLUN) SELF%XD2
READ (KLUN) SELF%XRHOLI
READ (KLUN) SELF%RDSRV
READ (KLUN) SELF%RDSCPD
READ (KLUN) SELF%RINVXP00
READ (KLUN) SELF%XMNH_TINY
READ (KLUN) SELF%XMNH_TINY_12
READ (KLUN) SELF%XMNH_EPSILON
READ (KLUN) SELF%XMNH_HUGE
READ (KLUN) SELF%XMNH_HUGE_12_LOG
READ (KLUN) SELF%XEPS_DT
READ (KLUN) SELF%XRES_FLAT_CART
READ (KLUN) SELF%XRES_OTHER
READ (KLUN) SELF%XRES_PREP
END SUBROUTINE

SUBROUTINE ACDC_COPY_CST_T (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (CST_T), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE







SUBROUTINE ACDC_WIPE_CST_T (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (CST_T), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
