MODULE MODE_TEST

IMPLICIT NONE

CONTAINS

SUBROUTINE SUB1(A, B)

USE MODE_MODULE1, ONLY : MODULE1_SUB1, &
& MODULE1_SUB3
USE MODE_MODULE2
USE YOMHOOK,    ONLY: LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE

REAL, INTENT(IN) :: A
REAL, INTENT(INOUT) :: B

IF (LHOOK) CALL DR_HOOK('SUB1',0,ZHOOK_HANDLE)

CALL MODULE2_SUB4(A)

CALL MODULE1_SUB3(A)

CALL MODULE1_SUB2(B)

IF (LHOOK) CALL DR_HOOK('SUB1',1,ZHOOK_HANDLE)

END SUBROUTINE

SUBROUTINE SUB2(A, B)

USE MODE_MODULE1
USE MODE_MODULE2, ONLY SUB2
USE YOMHOOK,    ONLY: LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE

REAL, INTENT(IN) :: A
REAL, INTENT(INOUT) :: B

IF (LHOOK) CALL DR_HOOK('SUB1',0,ZHOOK_HANDLE)


CALL MODULE1_SUB1(A)

CALL MODULE2_SUB2(B)

IF (LHOOK) CALL DR_HOOK('SUB1',1,ZHOOK_HANDLE)

END SUBROUTINE
END MODULE
